### ISSUE TITLE
Tombol "Ubah" dibuang saja jika tidak terpakai dan Kode Pemasok posisinya ditukar dengan Nama Pemasok

### ISSUE THREAD

**Issue by WinServer** [sevenzk/SJKTCI#10]
![image](https://user-images.githubusercontent.com/44515909/47599138-8c4c4100-d9d1-11e8-8209-fe4ee1fef478.png)

**Comment by fafn3r** [comment]
Tombol "Ubah" akan dipakai untuk Kode Pemasok, to be fixed

**Comment by WinServer** [comment]
Sudah ditukar posisinya namun belum dibuat untuk develop..

**Comment by sevenzk** [comment]
Tunggu program kelar developed.

**Comment by fafn3r** [comment]
kalau ganti kode barang, apakah barcode semua barcode (5 digit pertama) ikut diganti?

**Comment by fafn3r** [comment]
sudah dibuat di master barang satuan

**Comment by fafn3r** [comment]
sudah dibuat di master barang gabungan dan master induk barang satuan
