### ISSUE TITLE
[Sales Return] Barcode yang sudah dikembalikan apakah masih bisa digunakan atau tidak

### ISSUE THREAD

**Issue by WinServer** [sevenzk/SJKTCI#118]
Barcode barang gabungan jika sudah dijual dan dikembalikan maka harus dikembalikan satu paket sesuai dengan barcodenya.

Jika setelah barang setelah dikembalikan dan setelah pengecekan barang tersebut tidak rusak, apakah barcode dari barang tersebut mau digunakan kembali atau tidak?..

**Comment by sevenzk** [comment]
Yg di retur (kalo sudah ada form retur), mending barcode dibikin baru aja, jangan pake kode yang lama. Biar bisa tau ini barang bukan yg dulu.

Tapi kode alangkah baiknya kalo ada tanda bahwa itu barang retur gmn?

**Comment by WinServer** [comment]
Setuju untuk barcode baru jika barang tersebut rusak dan mau digunakan kembali.
Untuk informasi barcode lama akan dicatat pada saat sales retur namun untuk menu sales retur belum dibuat untuk saat ini..

**Comment by sevenzk** [comment]
sip, ditunggu sales retur klo gt

**Comment by WinServer** [comment]
Refer to issue #162
