### ISSUE TITLE
[Master Harga] Untuk barang composite 95% dari total harga komponen setelah dijumlahkan dan bisa diedit

### ISSUE THREAD

**Issue by WinServer** [sevenzk/SJKTCI#120]
Untuk harga barang composite akan mengambil 95% dari total harga jual komponen setelah pajak dan bisa diedit di master harga.

**Comment by WinServer** [comment]
Di bagian perincian ditambahkan informasi ongkir sebelum HPP..

**Comment by WinServer** [comment]
Perhitungan HPP menjadi 3 tahap :
1. Tahap pertama dimana semua komponen barang gabungan memiliki harga jual satuan sehingga akan dihitung 95% dari total harga jual.
Untuk informasi harga margin dan HPP akan dimunculkan dengan total

2. Tahap kedua dimana salah satu komponen barang gabungan tidak memiliki harga jual satuan maka harga jual barang gabungan akan bernilai 0 (akan dicoba terlebih dahulu). Untuk selanjutnya diisi manual angka laba atau harga jual W.

3. Tahap ketiga untuk barang set sama seperti tahap pertama perhitungannya. Jika harga jual satuan barang komponen bernilai 0 maka harga jual barang composite akan bernilai 0.

Konsep perhitungan untuk total HPP dan Harga Margin point 1,2, dan 3 sama..

**Comment by sevenzk** [comment]
Dah beres ini bung @fafn3r ?

**Comment by WinServer** [comment]
ini harusnya udah oleh bung @fafn3r , nanti ini gw yang cek..belum dicek kemarin..assigned to @WinServer ..

**Comment by sevenzk** [comment]
sip kalo udah beres tinggal di centang

**Comment by WinServer** [comment]
Hpp (total dari barang satuan) , Harga W (95% dari total), dan HET (dari W) sudah benar
