### ISSUE TITLE
Update Setting Rate ada error

### ISSUE THREAD

**Issue by WinServer** [sevenzk/SJKTCI#13]
![image](https://user-images.githubusercontent.com/44515909/47599262-2e6d2880-d9d4-11e8-9cc1-56e32904c211.png)

**Comment by fafn3r** [comment]
jika pencet "Perbarui", program akan mengupdate data Capital dan Price Level (semua barang dengan Capital Currency yang sesuai) berdasarkan Profit Percentage yang ditampilkan di program (untuk profit berdasarkan Capital akan dihitung dan disimpan tanpa ditampilkan)

**Comment by fafn3r** [comment]
fixed
