### ISSUE TITLE
[Penagihan & Master Pelanggan] Data Diskon Tambahan dan Denda bisa diedit

### ISSUE THREAD

**Issue by WinServer** [sevenzk/SJKTCI#130]
1. Untuk menu Penagihan, data diskon tambahan dan denda bisa diedit pada saat klik tombol **Edit**
![image](https://user-images.githubusercontent.com/44515909/53677247-6e744d00-3cdf-11e9-8535-abc779b9644c.png)

Pada saat klik tombol simpan ada perhitungan untuk nilai Diskon Tambahan dan Denda dimana nilai sebelumnya (awal) Diskon Tambahan dan Denda ditampung terlebih dahulu dan dikurangi dengan nilai yang sudah diedit.
Contoh : Nilai awal 10.000 mau diedit menjadi 5.000 maka nilai diskon tambahan di **Master Pelanggan** bertambah 5.000

2. Untuk menu Master Pelanggan, data diskon tambahan dan denda bisa diedit.

**Comment by WinServer** [comment]
Pada saat klik ubah, data Diskon Tambahan tidak bisa diisi angka / diedit.

**Comment by fafn3r** [comment]
Data Diskon Tambahan mengikuti total dari Diskon Tambahan pada [Penagihan] dan [Master Pelanggan]

**Comment by sevenzk** [comment]
sudah oke..
