### ISSUE TITLE
[Barang Drop Shipping] Barang Drop Shipping yang dikeluarkan tidak dibongkar

### ISSUE THREAD

**Issue by WinServer** [sevenzk/SJKTCI#133]
Ada barang drop shipping pada saat dijual / keluar dari toko (akan dipikirkan lebih lanjut)

Bagaimana cara membaca data barcode dari packing list (sama seperti membaca barcode ke item  composite)..

**Comment by sevenzk** [comment]
Sudah lama tidak mampir kesini, kira2 ini issue sbenernya apa yah hmmm?

**Comment by WinServer** [comment]
ini issue yang barangnya masuk misalnya 1 kardus (isi 100)..nanti pada saat dikeluarkan / dijual berupa 1 kardus tersebut (tidak per satuan)..ini kalau gak salah sudah diakalin dengan master item gabungan (menjadi item set)..

**Comment by sevenzk** [comment]
oh ini barang2 kaya donny pny yg mampir trus lgs kluar, ini bagusnya di labelin jg, trus di yoloin tempel2 karna sudah pny karyawannya.
