### ISSUE TITLE
[Penambahan Kode Barang] Ada penambahan kode barang di beberapa menu

### ISSUE THREAD

**Issue by WinServer** [sevenzk/SJKTCI#135]
Ada penambahan informasi data "Kode Barang" di beberapa menu seperti :
- Order Pembelian
- Daftar Pengepakan dan Barcode
- Penerimaan Barang di Gudang
- Perpindahan Barang ke Toko

**Comment by fafn3r** [comment]
Kode barang sudah ditambahkan juga pada Stok Gudang, Stok Toko, dan Penyesuaian Stok

**Comment by WinServer** [comment]
Done
