### ISSUE TITLE
[Master Harga] Pembulatan 1000 ke atas atau ke bawah di Harga Setelah Pajak

### ISSUE THREAD

**Issue by WinServer** [sevenzk/SJKTCI#136]
Ada pembulatan 1000 ke atas atau ke bawah (yang mendekati) di Harga Setelah Pajak seperti gambar di bawah:
![image](https://user-images.githubusercontent.com/44515909/54066707-6f6d2780-4267-11e9-94cf-e7aaefd315fb.png)

**Comment by fafn3r** [comment]
Pembulatan yang dimaksud hanya pembulatan ke atas (roundup)

**Comment by WinServer** [comment]
Done..
