### ISSUE TITLE
[Report Penagihan] Pembuatan report penagihan dengan format baru

### ISSUE THREAD

**Issue by WinServer** [sevenzk/SJKTCI#137]
Minta dibuatkan report penagihan dengan format baru yang sudah diberikan oleh surya.

**Comment by WinServer** [comment]
Masih ada kendala di bagian page header dan page footer dimana di report menjadi blank atau kosong untuk bagian page header dan footer

**Comment by fafn3r** [comment]
Report (Bon/Invoice) sudah dibuat dengan format baru dan 1 halaman dapat memuat sekitar 30 item/barang

**Comment by WinServer** [comment]
Done..sudah dibuatkan..
