### ISSUE TITLE
[Stok Movement] Kesan dan pesan setelah pemakaian

### ISSUE THREAD

**Issue by sevenzk** [sevenzk/SJKTCI#157]
Penerimaan barang:
- User tidak memperdulikan info yg di munculkan di kanan, dengan barangnya.
- Scan aga lelet untuk hotspot, ga tau kalau pakai smartfren dan semacamnya apa lebih baik.
- Info stelah scan nongol smua, bikin jadi lag.

Gudang ke toko:
- sama

Basically modelnya Stock Movement itu mesti dengan mindset PPOS, semuanya mesti keliatan gede, biar gampang untuk scannya. Basic needsnya cman scan, sisa yg blom ke scan nomor brp aja.

Barcode mesti ganti model jg, susah scan yg ini, terlalu tipis.

**Comment by sevenzk** [comment]
Di penerimaan barang, No. GR dan No. PO tidak diperlukan.
Karyawan kerjaannya cman scan masuk kelar.

**Comment by WinServer** [comment]
Design sudah dirubah sesuai dengan permintaan..
