### ISSUE TITLE
[Sales Retur] Perlu ada ini

### ISSUE THREAD

**Issue by sevenzk** [sevenzk/SJKTCI#162]
sudah ada yg retur, gara2 ayu salah input barang jadi dipulangin *slap face*

**Comment by WinServer** [comment]
perlu dibahas lebih lanjut untuk sales retur..

**Comment by sevenzk** [comment]
Proses sales retur:
1. Barang yang dikembalikan akan di scan kembali
2. Program akan mengecek apakah barcode tersebut ada di penjualan atau tidak (akan menarik semua informasi penjualan berupa nomor order, nomor invoice, nama customer, qty, dan harga)
3. Jika tidak ada maka akan ada notifikasi "Kode barcode tidak ditemukan di penjualan" dan barang tidak diterima
4. Batas waktu barcode kembali adalah 2 tahun (untuk semua barang) => Akan dicek ke data penjualan dan jika > 2 tahun akan ada notifikasi "Barang tersebut sudah lebih dari 2 tahun"
5. Di menu pengaturan ditambahkan informasi untuk batas waktu pengembalian barang (mengacu point no 4)
6. Setelah di scan, user harus memilih jenis retur diantaranya:
 a. Barang kembali dan ditukar dengan barang yang sama (stok tidak berubah)
 b. Barang kembali, ditukar dengan baru dan barang lama dibuang (stok berkurang)
 c. Barang dibuang (stok tidak berubah) => Akan didiskusikan kembali
 d. Barang kembali dan disimpan kembali (stok bertambah)
 e. Barang kembali (dibuang karena rusak) dan ditukar dengan barang yang berbeda (untuk barang parent) => stok barang yang kembali tidak bertambah dan stok barang yang ditukar berkurang
 f. Barang kembali (masuk ke stok toko) dan ditukar dengan barang yang berbeda (untuk barang parent) => stok barang yang kembali bertambah dan stok barang yang ditukar berkurang
7. Setelah dipilih untuk jenis retur dan isi catatan (untuk menentukan barang yang mau ditukar) maka akan ada tombol "Simpan" dimana tombol simpan akan men-generate nomor Retur (insert data baru) dan mempengaruhi stok berdasarkan jenis retur
8. Pada saat pergantian barang, user akan melakukan penginputan di program "Order Entry" pada bagian menu "Retur" (menggantikan menu cetak) seperti gambar di bawah:
![image](https://user-images.githubusercontent.com/14845394/57965240-cd0aa800-796b-11e9-9d35-3937e3ff5a0f.png)

9. Pada menu riwayat retur, sudah tertulis list barang yang dikembalikan (jenis retur untuk point a dan b pada nomor 6) dan catatan note
10. User menambah barang yang mau digantikan untuk di scan barcode

**Comment by WinServer** [comment]
Format bon retur akan diberikan oleh surya untuk diberikan ke bung @fafn3r

**Comment by WinServer** [comment]
Untuk design sales retur seperti gambar di bawah :
![image](https://user-images.githubusercontent.com/44515909/64903679-631ac900-d6e7-11e9-8eb0-f8d8e52e7589.png)
Proses :
1. Klik tambah maka nomor retur akan terbentuk secara otomatis dan tanggal retur akan terbentuk hari ini (bisa diedit)
2. Tombol delete berfungsi untuk menghapus detil retur. Jika klik tombol delete dan sudah ada barcode di detil pengembalian barang maka akan menghapus semuanya
Detil nomor retur seperti gambar di bawah :
![image](https://user-images.githubusercontent.com/44515909/64903759-ceb16600-d6e8-11e9-88c2-e0f954fd4224.png) 

Untuk Detil Pengembalian Barang seperti gambar di bawah :
![image](https://user-images.githubusercontent.com/44515909/64903937-18e81680-d6ec-11e9-8fc7-c39d5d868793.png)
Proses :
1. Setelah ada nomor retur, maka user memilih tipe retur dan melakukan scan barcode untuk barang yang dikembalikan
2. Jika tipe retur kembali dan ditukar dengan barang baru maka user harus melakukan scan barcode di bagian "**Penukaran Barang**" terlebih dahulu sebelum melakukan scan barcode kembali barang lainnya 
3. Jika tipe retur kembali dan ditukar dengan barang baru maka setelah user scan barcode di pengembalian barang, textbox scan barcode di pengembalian barang menjadi disable dan textbox scan barcode di penukaran barang menjadi enable.

Untuk Detil Penukaran Barang seperti gambar di bawah :
![image](https://user-images.githubusercontent.com/44515909/64903956-5187f000-d6ec-11e9-8c99-26cbdc568783.png)
Proses :
1. Jika tipe retur kembali dan ditukar dengan barang baru maka setelah user scan barcode di penukaran barang, textbox scan barcode di pengembalian barang menjadi enable dan textbox scan barcode di penukaran barang menjadi disable.

**Comment by fafn3r** [comment]
setelah direnungkan nampaknya perlu ada perubahan konsep; konsep yang ada sekarang mungkin lebih cocok diterapkan untuk program utama (pos); usulan perubahan konsepnya menjadi:
- retur dibuat dengan konsep seperti order penjualan pada program spos (form retur hanya akan menampung 1 retur) 
- setelah selesai mengerjakan retur, retur akan dikirim dar program order entry ke program utama (pos) untuk ditinjau, dikunci (eksekusi pergerakan stok), dan dicetak

**Comment by WinServer** [comment]
hmm..konsepnya mau dirubah menjadi lebih simpel?..
apakah ada kendala dengan konsep sebelumnya (dari sisi user dan program) ?..
kenapa lebih cocok di PoS?..

ini pertanyaan untuk diskusi ya bukan menolak usulan (takut salah tangkap)..

**Comment by WinServer** [comment]
**Item Composite**
Untuk hal ini ada perubahan dimana pada saat scan barcode di order entry (khusus untuk barang composite) tidak ada pengecekan barang yang ditukar. Kondisi :
1. Tidak ada pengecekan untuk saat ini untuk barang composite dikarenakan belum ada composite parent.

**Item Single**
pengecekan barang yang ditukar dengan barang berbeda hanya untuk item single (pengecekan ke parent). Kondisi :
1. Jika barang berbeda namun satu parent yang sama maka diperbolehkan, jika tidak maka tidak diperbolehkan untuk ditukar 

**SJKTCI PoS**
Kondisi :
1. Untuk SJKTCI PoS, lnformasi yang dibuat untuk sales retur menjadi :
![image](https://user-images.githubusercontent.com/44515909/70844103-ca732100-1e6e-11ea-92d6-898e4cb97814.png)

2. Untuk detilnya sebagai berikut :
![image](https://user-images.githubusercontent.com/44515909/70844123-0312fa80-1e6f-11ea-9fbd-3cb7250d4a4a.png)

**Comment by WinServer** [comment]
tambahan informasi :
1. Untuk master item composite tidak akan ada pengecekan barang merefer ke point ke **Item Composite** di atas sehingga harus ada pengecekan dari admin untuk barang composite untuk saat ini sambil dibuatkan ada composite parent untuk item composite ini yang mau di retur

2. Untuk yang SJKTCI PoS, tombol Ubah, Hapus, Simpan, dan Batal akan dihilangkan karena setelah dilihat keperluan admin hanya ngeprint sebagai tanda bukti.

Mohon masukan dan koreksinya ya jika ada masukan-masukan...

**Comment by fafn3r** [comment]
barusan ada diskusi dengan surya, mungkin untuk item composite, dibuatkan form tambahan (pop up) pada order entry untuk menentukan jenis retur setiap komponennya?

**Comment by sevenzk** [comment]
> dibuatkan form tambahan (pop up) pada order entry untuk menentukan jenis retur setiap komponennya?

Apakah itu dikerjakan di waktu yg sama apa beda?

Lebih baik di waktu yg sama ya?

**Comment by WinServer** [comment]
iyah lebih baik di waktu yang sama..

**Comment by sevenzk** [comment]
Woke kalo gt

**Comment by WinServer** [comment]
Untuk saat ini sudah bisa untuk barang single yang sama..
Untuk yang composite akan dibuatkan composite parent di table yg sama (Master_Parent_Item_Single)

Saran saja apakah memungkinkan table Master_Parent_Item_Single bisa dirubah menjadi Master_Parent?..Jika rubahnya banyak maka tidak usah dirubah.

ada penambahan field untuk master_parent_item_single yaitu Type dengan tujuan membedakan mana yang merupakan item single dan item compsite..

Untuk Master Harga Parent Composite, konsepnya sama seperti item single parent dimana parent akan mengambil harga pertama kali dari child item composite yang didaftarkan pertama kali dan child item composite kedua akan mengikuti harga selanjutnya..

Jika ada barang composite di retur maka barang composite akan dikembalikan semua dan akan ditukar dengan yang terdaftar di master parent. Jika tidak terdaftar maka harus didaftarkan terlebih dahulu. Jika tidak maka tidak akan keluar list nya.

**Comment by fafn3r** [comment]
report sudah dipush ke live

**Comment by sevenzk** [comment]
https://cdn.discordapp.com/attachments/673030324598341663/676689505553743892/unknown.png

perlu angka nilai barangnya dsini. kalo campuran 1 jenis barang ada yg disimpan, ditukar dan di buang, brarti yg ada nilainya aja yg jumlahkan

**Comment by fafn3r** [comment]
sudah ditambahkan filter pada Pengembalian yang mengharuskan pelanggan pada retur dan penjualan sama.

**Comment by fafn3r** [comment]
sudah ditambahkan harga jual dan total, dengan harga jual ditampilkan sesuai penjualan untuk barang yang tidak ditukar dan ditampilkan sebagai 0 untuk barang yang ditukar

**Comment by WinServer** [comment]
1. Pada saat order entry ada muncul pop menu baru jika barang tersebut merupakan barang composite (gabungan).
2. Tampilan Pop up menu yang muncul adalah sebagai berikut:
![image](https://user-images.githubusercontent.com/44515909/88449448-2c6a1f00-ce71-11ea-8c3d-bb7d6c224df6.png)

3. Setelah tekan tombol simpan maka akan muncul di grid menu pengembalian di order entry untuk barang gabungan tersebut.
4. Jika opsi tersebut tidak bisa maka akan dibuat muncul pop up satu per satu.

**Comment by WinServer** [comment]
patch terbaru sudah ditambahkan untuk composite dimana untuk barang composite sudah bisa diretur.
Untuk stok sudah oke untuk 4 jenis pengembalian..
