### ISSUE TITLE
[Pengiriman Barang] Kunci ga sesuai keinginan

### ISSUE THREAD

**Issue by sevenzk** [sevenzk/SJKTCI#163]
Kunci kan mengurangi stok barang, tapi harusnya ga boleh sampai minus, brarti mesti di fix ini. Kaliper 2P slim diambil hari sabtu tapi ga scan barcode, jadinya minus.

**Comment by WinServer** [comment]
akan ditambahkan validasi pada saat kunci jika stok < 0 maka keluar warning "Barang tidak bisa dikirim dikarenakan stok tidak mencukup untuk barang : A"..

**Comment by WinServer** [comment]
Baru akan dilakukan setelah proses stock opname..stock opname dilakukan tgl 15 Mei ke atas..

**Comment by WinServer** [comment]
untuk POS  80% untuk barang yang laku dijual sudah beres, untuk SJKTCI masih ada sedikit selisih barang namun tidak terlalu banyak..

akan ada dilakukan proses stock opname lagi..

**Comment by WinServer** [comment]
sudah muncul validasi seperti gambar berikut:
![image](https://user-images.githubusercontent.com/44515909/87128419-cb134f00-c2b9-11ea-89f3-447ecf4cac57.png)

sudah bisa di push untuk hal ini..
