### ISSUE TITLE
[Stok movement] Perlu informasi lebih lanjut

### ISSUE THREAD

**Issue by sevenzk** [sevenzk/SJKTCI#165]
![Capture](https://user-images.githubusercontent.com/14845394/56122283-43e30880-5f9c-11e9-8db8-e76ca6bb388a.PNG)

- Informasi di sebelah kanan dan kiri perlu di jelaskan, yg kiri itu masih di gudang, yg kanan sudah diambil.

- Kayanya dropdown kaya gitu bisa ribet deh kedepannya. Soalnya anggap udah 20 kali datang, ntar jadi mesti dicari 1 1 barang tersebut dari supplier mana, apa bs per supplier di jadiin 1? Ada kendala ga kalo kaya gini?

**Comment by WinServer** [comment]
Untuk ke depannya tampilannya sebagai berikut :
![image](https://user-images.githubusercontent.com/44515909/64469332-47994680-d15a-11e9-9500-d4e87f5fa77b.png)

**Comment by WinServer** [comment]
untuk hal ini sudah dicoba namun ada sedikit kekurangan jika ada scan barcode di bagian Masuk Gudang dan Barcode tersebut tidak ada maka tidak keluar notifikasi "Barcode Tidak Ditemukan"..
