### ISSUE TITLE
[Print Penagihan] Kepotong nama tokonya

### ISSUE THREAD

**Issue by sevenzk** [sevenzk/SJKTCI#168]
![Capture](https://user-images.githubusercontent.com/14845394/56483233-ce72bd00-64f2-11e9-973e-9d7dcabf8d55.PNG)

**Comment by WinServer** [comment]
Masih ada yang kepotong untuk CV. Surya Persada menjadi CV. Surya Per

**Comment by WinServer** [comment]
sudah diselesaikan dan dicoba..
