### ISSUE TITLE
Format tanggal

### ISSUE THREAD

**Issue by sevenzk** [sevenzk/SJKTCI#169]
Untuk so, pengiriman dan penagihan biasa dsb dsb yg tidak berhub dgn barcode, mungkin bisa diganti biasa aja

SO-19050001

19 tahun, 05 bulan, 001 itu tanggal, dpt limit per bulan 9999.

Terlalu detil kayanya kalo kaya barcode.

**Comment by WinServer** [comment]
sudah diganti nomor ordernya..
