### ISSUE TITLE
[Packing Barcode List] Perubahan fitur pada saat penginputan barang di karton

### ISSUE THREAD

**Issue by sevenzk** [sevenzk/SJKTCI#175]
Cara input barang sesudah generate barcode diubah menjadi 2 cara yaitu:
1. Cara pertama:
 a. Pilih barang terlebih dahulu
 b. Isi Quantity barang
 c. Isi karton awal dan karton akhir sehingga membutuhkan 2 textbox untuk mengisi karton awal dan akhir

2. Cara kedua:
 a. Pilih barang terlebih dahulu
 b. Isi Quantity barang
 c. Keluar dgv yang berisikan list karton untuk dipilih oleh user dan ada tombol add untuk generate barang (nama barang dan qty) sesuai list karton

sementara akan dibuat untuk cara pertama terlebih dahulu dan akan diukur waktunya, dikarenakan saat ini pembuatan list data barang membutuhkan waktu kurang lebih 3 jam.

**Comment by WinServer** [comment]
ini sudah menggunakan cara kedua..
