### ISSUE TITLE
[Riwayat Penjualan] Perubahan format pada riwayat penjualan

### ISSUE THREAD

**Issue by sevenzk** [sevenzk/SJKTCI#177]
untuk riwayat penjualan ditambahkan search untuk nomor invoice, nomor pengiriman, dan nomor order dalam satu textbox seperti gambar di bawah:
![image](https://user-images.githubusercontent.com/14845394/57964740-72ba1900-7964-11e9-96a9-24d72213a7a9.png)

**Comment by WinServer** [comment]
sudah dicoba dan oke..
