### ISSUE TITLE
[Riwayat Barcode] tidak perlu data dgv untuk list data barcode

### ISSUE THREAD

**Issue by sevenzk** [sevenzk/SJKTCI#178]
Dgv di menu riwayat barcode diubah menjadi beberapa textbox dengan informasi sebagai berikut:
- Kode Barang
- Nama Barang
- Nama yang mengerjakan (contoh : dodi)

**Comment by WinServer** [comment]
Ada penambahan informasi :
- Tanggal kirim
- Nomor kirim
- Tanggal tagihan
- Nomor tagihan

**Comment by WinServer** [comment]
sudah ditambahkan informasinya..
