### ISSUE TITLE
[Delete Barcode] Hapus barcode yang tidak dikirim ke PoS

### ISSUE THREAD

**Issue by WinServer** [sevenzk/SJKTCI#179]
Ada fitur buat hapus barcode yang tidak dikirim ke konfirmasi..proses hapus ini terjadi pada saat klik tombol kirim ke PoS..

sehingga barcode yang sudah dihapus bisa digunakan kembali untuk scan berikutnya..

**Comment by WinServer** [comment]
Proses penghapusan diubah menjadi  :

1. Di konfirmasi, pada saat klik tombol "Kirim" maka ada validasi untuk melakukan pengisian password user tersebut jika masih ada sisa barcode yang belum di scan di konfirmasi.

2. Sesudah melakukan pengisian password maka barcode yang tidak dikirim akan dihapus dengan tujuan barcode tersebut bisa digunakan dan discan kembali

3. Jika semua barcode di konfirmasi sudah di scan maka tidak perlu muncul pengisian password user dan bisa langsung kirim setelah klik tombol "Ya"..

**Comment by sevenzk** [comment]
Dah beres ini blum yah? Apa masih ada update lagi?

**Comment by WinServer** [comment]
kalau belum ada label fixed sepertinya ini belum sur..nanti coba bung @fafn3r bantu update ya, mungkin sudah pernah dibuat namun belum dicek atau gmn..

**Comment by WinServer** [comment]
Untuk hal ini, jika ada barcode yang tidak terkirim dan dihapus dari konfirmasi maka ada pencatatan di activity log untuk barcode mana yang dihapus sehingga jika ada kendala user kesulitan barcode mana yang tidak terkirim maka bisa dilihat di activity log.

**Comment by fafn3r** [comment]
Sudah dimodifikasi untuk mengakomodasi barang yang diambil tapi tidak dikonfirmasi (barcode tetap bisa dipakai)

**Comment by WinServer** [comment]
sudah bisa dan dites barang di konfirmasi disisakan satu barcode di sebelah kiri (VBK0619N0231) untuk barang Van Belt Kevlar Scoopy F1..Kemudian kirim ke PoS dan dicoba dari pesan order untuk barang tersebut dan di scan kembali untuk barcode VBK0619N0231 (bisa masuk di ambil order dan konfirmasi)..
