### ISSUE TITLE
[Master Barang] Input kode barang

### ISSUE THREAD

**Issue by sevenzk** [sevenzk/SJKTCI#184]
Kedepannya smua barang mau punya kode barang, ini beda ama barcode yah.

Jadi kalo gua bikin kode barang itu suka comot2 dari nama barangnya atau pake bahasa inggris atau dari supplier codenya.

Contoh BLK-15, HK-155, itu kode BLK dan HK itu kedepannya nanti kalo udah itemnya makin menambah takutnya kedobel. So far gua udah ada kedobel karna manual.

Apa di bagian item barang nantinya bisa di aplikasi 1 tempat untuk ini?

Jadi kalo ada barang yg punya kode BLK, gua input barang laen dgn BLK lagi pas mau save kena error blgnya "kode sudah dipakai" atau semacamnya.

Ga urgent cman improvement hidup aja.

**Comment by WinServer** [comment]
Done..
