### ISSUE TITLE
[Master Item Satuan] Ditambahkan flag agar tidak bisa dijual satuan

### ISSUE THREAD

**Issue by WinServer** [sevenzk/SJKTCI#186]
Ditambahkan flag di master barang satuan dengan tujuan agar barang tersebut tidak bisa dijual satuan / terpisah.

**Comment by WinServer** [comment]
masih muncul di pesan order PPOS (order entry)

**Comment by fafn3r** [comment]
fixed, belum dipush

**Comment by WinServer** [comment]
sudah di push..
