### ISSUE TITLE
[Pengiriman] & [Penagihan] Ditambahkan tombol hapus barang

### ISSUE THREAD

**Issue by fafn3r** [sevenzk/SJKTCI#188]
- Ditambahkan 2 tombol untuk menghapus barang yang dipilih:
1. Hapus per barcode (untuk pengembalian sebagian qty barang)
2. Hapus satu barang secara keseluruhan (untuk pengembalian semua qty 1 jenis barang)
- Data dihapus sampai ke order entry (pesan, ambil, konfirmasi)

**Comment by WinServer** [comment]
kalau ada permintaan pertukaran barang oleh customer, maka harus membuat order baru (tidak bisa ditukar)..

**Comment by WinServer** [comment]
sudah boleh di close kah issue ini?.. @sevenzk
