### ISSUE TITLE
[Barang Induk] Konsep Barang Induk

### ISSUE THREAD

**Issue by fafn3r** [sevenzk/SJKTCI#191]
Kondisi sekarang:
Barang yang dapat dijadikan induk-turunan adalah barang yang harga belinya sama (perbedaan harga beli berarti HPPnya berbeda) walaupun harga jualnya sama

**Comment by fafn3r** [comment]
- Untuk barang parent, yang diedit adalah harga W setelah pajak, baru menghitung laba % masing2 childnya
- Perlu ditambahkan tombol untuk menampilkan form baru yang berfungsi untuk melakukan simulasi perhitungan harga (seperti harga barang satuan non child)

**Comment by WinServer** [comment]
barang induk sekarang digunakan untuk mengupdate harga child-nya..
