### ISSUE TITLE
[Master Harga] Konsep Capital

### ISSUE THREAD

**Issue by fafn3r** [sevenzk/SJKTCI#196]
- Nilai capital di master harga apakah sama dengan harga beli pada order pembelian?
- Jika sama, apakah mau langsung diupdate setiap ada pembelian?

**Comment by fafn3r** [comment]
- Untuk barang parent, yang diedit adalah harga W setelah pajak, baru menghitung laba % masing2 childnya
- Perlu ditambahkan tombol untuk menampilkan form baru yang berfungsi untuk melakukan simulasi perhitungan harga (seperti harga barang satuan non child)

**Comment by fafn3r** [comment]
- Capital diganti menjadi harga beli
- Update harga beli dengan harga terbaru dari order pembelian

**Comment by fafn3r** [comment]
capital sudah diganti menjadi harga beli

**Comment by WinServer** [comment]
Done..
