### ISSUE TITLE
[Warehouse To Store] Data Barcode dari Gudang

### ISSUE THREAD

**Issue by fafn3r** [sevenzk/SJKTCI#198]
Ada kendala saat scan barcode dari gudang (Warehouse to Store) karena harus memilih <nomor order - supplier> sebelum scan barcode

**Comment by WinServer** [comment]
Tidak perlu memilih nomor - supplier lagi, langsung ditampilkan semua jadi satu

**Comment by WinServer** [comment]
refer to issue #165
