### ISSUE TITLE
[Master Pemasok] Narahubung blum dikunci

### ISSUE THREAD

**Issue by sevenzk** [sevenzk/SJKTCI#2]
Bisa save tanpa nama supplier, kayanya biar rapi mending mesti ada datanya supplier jg deh.

**Comment by fafn3r** [comment]
- proteksinya kalau nama supplier ga diketik apa2, ga bisa disave, kalau ada karakter " " (spasi) udah dianggep ada karakter jadi bisa disave
- kunci narahubung yg dimaksud yg gimana ya?

**Comment by sevenzk** [comment]
- Hmm, bisa input chinese character ga?

- Kalo dulu ga ada nama kan ga bisa save, tp lu blg ada spasi brarti udah dianggap ada kata, ya udah gitu aja gpp.

**Comment by fafn3r** [comment]
Proteksinya cuman di Nama sama Kode Supplier, harus diisi baru bisa save
Nama Supplier dan Narahubung udah bisa save chinese character

**Comment by fafn3r** [comment]
to be continued in #20
