### ISSUE TITLE
[Master Supplier] Perlu bisa input chinese character

### ISSUE THREAD

**Issue by sevenzk** [sevenzk/SJKTCI#20]
![bug](https://user-images.githubusercontent.com/14845394/47847983-78ed0b80-ddff-11e8-8722-0321de0e8c69.JPG)

**Comment by fafn3r** [comment]
SJKTCI_PoS done
KTCRacing_PoS mau dibuat juga berarti ya?

**Comment by sevenzk** [comment]
Buat ini kayanya ga usah dl deh, buat SJKTCI aja,
