### ISSUE TITLE
[Permission] Penambahan Permission 

### ISSUE THREAD

**Issue by fafn3r** [sevenzk/SJKTCI#200]
Perlu ada penambahan permission untuk Add, Edit, dan Delete secara global

**Comment by sevenzk** [comment]
[Centang](http://imgur.com/a/r2GyF8f)

**Comment by sevenzk** [comment]
Mohon maap ga bisa upload gambar dari handpone pny openhub

**Comment by fafn3r** [comment]
sudah dibuat untuk pemisahan user permission, ada sedikit kendala pada form daftar pengepakan dan barcode, akan diperbaiki dalam waktu dekat

**Comment by WinServer** [comment]
sudah ditambahkan di SJM dan SJKTCI..
