### ISSUE TITLE
[Ambil & Konfirmasi] Penghapusan fitur ...

### ISSUE THREAD

**Issue by fafn3r** [sevenzk/SJKTCI#201]
Tombol ... pada ambil order dan konfirmasi order agar dihapus untuk 'memaksakan' prosedur pengerjaan order menjadi FIFO

**Comment by WinServer** [comment]
masih dibuka hanya untuk beberapa user (dalam hal ini mba ayu yang bisa klik)..

**Comment by WinServer** [comment]
mau ditaruh di setting dimana settingan tersebut berfungsi untuk membatasi 5 customer di ambil order dan konfirmasi order..

**Comment by WinServer** [comment]
di hold sampai ada keputusan minta dihilangin..atau mau ditaruh di setting..

**Comment by sevenzk** [comment]
tak terpakai dulu
