### ISSUE TITLE
Perhitungan Stok Barang Gabungan

### ISSUE THREAD

**Issue by fafn3r** [sevenzk/SJKTCI#205]
Jika ada barang gabungan yang terjual, perhitungan stok barang gabungan hanya menghitung jumlah barang gabungan tersebut, bukan semua barang gabungan yang menggunakan komponen gabungannya

**Comment by WinServer** [comment]
sudah okeh..
Hasil testing :
- Pembuatan 2 barang gabungan yang masing-masing terdiri dari 2 detil komponen yang sama
- Pembuatan penjualan barang untuk 1 barang gabungan
- Pengurangan quantity sama untuk 2 barang gabungan tersebut
