### ISSUE TITLE
[Pengiriman Barang] Kunci Order

### ISSUE THREAD

**Issue by fafn3r** [sevenzk/SJKTCI#208]
Kunci Order dapat ditekan berkali-kali saat proses penguncian, sehingga proses terhenti dan terjadi pemotongan stok berulang kali dari awal

**Comment by fafn3r** [comment]
Tombol kunci langsung dinon-aktifkan setelah ditekan, dan ditambahkan progress bar setelah tombol kunci ditekan

**Comment by WinServer** [comment]
Done..
