### ISSUE TITLE
[Pembayaran] Di menu pembelian ditambahkan menu pembayaran

### ISSUE THREAD

**Issue by WinServer** [sevenzk/SJKTCI#212]
Ditambahkan menu pembayaran seperti gambar di bawah :
![image](https://user-images.githubusercontent.com/44515909/61990013-8075d400-b062-11e9-9049-e201d0fde31a.png)

pada menu pembayaran akan ditampilkan sebagai berikut :
![image](https://user-images.githubusercontent.com/44515909/61990074-7e604500-b063-11e9-85fe-851ab08e77cb.png)

grid sebelah kiri berisi informasi invoice seperti gambar di bawah:
![image](https://user-images.githubusercontent.com/44515909/61990046-f5490e00-b062-11e9-84fb-f01f46cbc063.png)

grid sebelah kanan berisi informasi barang yang disertakan informasi pemasok seperti gambar di bawah:
![image](https://user-images.githubusercontent.com/44515909/61990049-0bef6500-b063-11e9-8e73-91f1900b12c3.png)

prosesnya adalah sebagai berikut :
1. Klik tambah sebelah kiri untuk melakukan pengisian tanggal invoice dan nomor invoice
2. Setelah diisi grid sebelah kiri, klik tambah sebelah kanan untuk memilih pesanan mana yang mau diambil dari data menu pesanan.  Form carinya seperti berikut :
![image](https://user-images.githubusercontent.com/44515909/61990037-d2b6f500-b062-11e9-8ec1-291da9a5118e.png)

3. Semua barang akan ketarik dari yang sudah ada di menu pesanan dan bisa diedit qty dan harganya.
4. Jika mau menambahkan barang maka invoice tersebut harus dikembalikan ke menu Pesanan terlebih dahulu baru menambah barang
5. Untuk menu pesanan dan pembayaran dijadikan satu tabel di Purchase Order seperti halnya Sales Order

**Comment by sevenzk** [comment]
Mau gua angkat lagi di bagian ini, di bagian mata uang knp perlu di kasih drop down lagi yah? Incase penawaran di dolar, trus bayarnya pakai NT kah?

**Comment by WinServer** [comment]
dibuat auto pada saat add data..

**Comment by WinServer** [comment]
Sudah dites..untuk sekarang, combo box untuk pemilihan mata uang dihilangkan namun masih memunculkan informasi mata uang yang otomatis diambil dari pesanan..
