### ISSUE TITLE
[Master Induk Barang Satuan] Ada pesan saat menambahkan child baru

### ISSUE THREAD

**Issue by WinServer** [sevenzk/SJKTCI#218]
Pada menu master induk barang satuan, ada pesan yang memilih apakah barang tersebut mau dihitung dengan harga parent atau tidak. Jika iya maka akan dihitung, jika tidak maka harga barang tersebut tidak dihitung..

**Comment by fafn3r** [comment]
jika iya -> harga jual disamakan (save)
jika tidak -> tidak jadi ditambahkan (cancel)

**Comment by WinServer** [comment]
sudah terhitung mengikuti yang ada..namun ada issue baru..
