### ISSUE TITLE
[Item Gabungan] Fitur menggabungkan beberapa barcode menjadi 1 barcode

### ISSUE THREAD

**Issue by WinServer** [sevenzk/SJKTCI#220]
Ada barang yang mau dijual per pack (sebagai contoh : 1 pack berisi 5 pcs / 10 pcs) dengan proses kerja sebagai berikut :
1. Untuk awal akan didaftarkan di item gabungan (contoh : handgrip dibuat dengan kode HANDGR dengan jumlah 10) seperti gambar di bawah:
![image](https://user-images.githubusercontent.com/44515909/62817392-efbdee80-bb5f-11e9-933c-a5da24f36fd0.png)

2. Setelah didaftarkan, barcode induk akan didaftarkan terlebih dahulu di program order entry dengan nama menu "Daftar Barcode" seperti gambar di bawah:
![image](https://user-images.githubusercontent.com/44515909/62817834-251a0a80-bb67-11e9-9881-d5d7e79fcadf.png)

3. Isi dari daftar barcode adalah sebagai berikut:
![image](https://user-images.githubusercontent.com/44515909/62817479-d7e76a00-bb61-11e9-9eb2-25ff8c5dbad1.png)

4. Detilnya adalah sebagai berikut:
![image](https://user-images.githubusercontent.com/44515909/62817486-eafa3a00-bb61-11e9-9b7c-9857d58c6c2b.png)

5. Cara kerjanya adalah User akan mendaftarkan terlebih dahulu barcode induknya dengan klik tombol "**Tambah**" kemudian user scan barcode induk untuk didaftarkan.

6. Setelah barcode induk terbentuk, maka user akan melakukan scan barcode untuk didaftarkan di anak barcode sehingga tampilannya menjadi sebagai berikut :
![image](https://user-images.githubusercontent.com/44515909/62817849-a83b6080-bb67-11e9-8be7-2a9df497280c.png)

7. Pada bagian barcode induk, data yang sudah dikirim dari menu konfirmasi ke PoS akan hilang dari "Daftar Barcode". Ada Flag di tabel Daftar Barcode yang menandakan bahwa barcode dan barang tersebut sudah dikirim ke PoS.

8. Pada Pesan Order, barang yang didaftarkan adalah barang gabungan tersebut.

9. Pada Ambil Order dan Konfirmasi Order, barcode yang didaftarkan adalah barcode induknya.

10. Pada Sales Order, barang yang dimunculkan adalah barang gabungan bukan barang satuannya.

11. Jika ada proses retur, baru bisa ditrack dari anak barcodenya.

**Comment by WinServer** [comment]
Untuk hal ini apakah tetap mau dibuat di master item gabungan atau terpisahkah untuk barangnya?..
jika tetap di master item gabungan maka flownya adalah:

1. Daftarin kode barang di master barang gabungan (seperti item set) dengan mencentang flag barang paket untuk menandakan barang tersebut merupakan barang paket
2. Cetak barcode seperti biasa di program last generated barcode (parent dan child barcode)
3. Admin order entry mendaftarkan parent barcode dan child barcode di menu daftar barcode
4. Admin pesan order mengisi kode barang berdasarkan parentnya
5. Untuk ambil order apakah yang dimunculkan mau parent barcodenya atau childnya?.. Jika parent barcodenya maka ada potensi seperti diskusi kemarin dimana akan kesulitan saat mau menghapus child barcodenya.
Contoh : 1 Parent Barcode = 10 Child Barcode
6. Jika yang ditampilkan di data adalah child barcode maka proses dari ambil order sampai konfirmasi order, barcode yang ditampilkan adalah anaknya (10 Barcode).

**Comment by sevenzk** [comment]
1. Pisah

2. Yep betul

3. Admin order entry bikin Paket barcode, Single ke paketnya itu masing2 lantai

4. aga ga mudeng, jadi yg bikin pesan order kan tetep tulis "Dop Busi"?

5. Saat ambil sih harusnya parent, tapi open for suggestion ini.

6. ini masih ngikut nomor 5 ya

Bung fred ada komen?

**Comment by WinServer** [comment]
1. okeh nanti ada 1 menu lagi buat daftarin barang paket ini

2. Deal

3. okeh nanti akan dipasangkan di daftar barcode

4. nanti yang keluar barangnya adalah nama yang didaftarkan (misal : Paket Dop Busi) atau bisa diakalin yang keluar tetap dop busi tapi dengan ketentuan di master item satuan (Dop Busi) ada penanda bahwa barang tersebut paket sehingga pembacaan barcodenya ke daftar barcode (ini sudah menjadi ranah teknis)

5. Kalau menurut gw si child, mungkin ada masukan dari bung @fafn3r untuk sisi programnya ada kesulitan dmn.

6. Yup, no 6 akan mengikuti dari point 5.

**Comment by fafn3r** [comment]
Sedikit diskusi mengenai ini:
- Pesan order akan mengisi order seperti biasa, tidak ada perubahan
- Ambil order bisa scan paket maupun komponennya satu per satu
- Jika Ambil order scan paket, konfirmasi juga akan scan paket dan hasilnya akan terpisah menjadi komponen-komponen paketnya

**Comment by WinServer** [comment]
Ada tambahan component Number di table Packet_Component_Pairing yang bertujuan sebagai security supaya datanya rapi dan benar

**Comment by WinServer** [comment]
Done..
