### ISSUE TITLE
Penambahan tombol Search untuk semua textbox Search

### ISSUE THREAD

**Issue by fafn3r** [sevenzk/SJKTCI#222]
Menghindari terjadinya lag setiap kali mengetik 1 karakter setelah 3 karakter awal

**Comment by WinServer** [comment]
refer to #227

**Comment by WinServer** [comment]
Hal ini diutamakan untuk PoS SKI dan SJM terlebih dahulu.

**Comment by WinServer** [comment]
sudah diimplementasi di PoS SKI dan SJM.
