### ISSUE TITLE
[Samples & Losses] 

### ISSUE THREAD

**Issue by fafn3r** [sevenzk/SJKTCI#224]
Perlu fitur ini untuk keperluan big boss memberikan sample

**Comment by WinServer** [comment]
ada 2 pilihan :
1. Lewat Order Entry
2. Lewat menu Sample / Losses di PoS

enakan yang mana ya idenya.. @sevenzk

**Comment by fafn3r** [comment]
Loss done di PoS
Sample/Sponsor sepertinya perlu 3 fasa seperti pesan -> ambil -> konfirmasi

**Comment by fafn3r** [comment]
Sample/Sponsor sudah ditambahkan sebagai percabangan dari order entry biasa (proses mengikuti order entry seperti biasa, tapi masuk ke tabel yang berbeda dan form yang berbeda pada PoS)

**Comment by fafn3r** [comment]
report dan riwayat belum dibuat

**Comment by WinServer** [comment]
Untuk Pemotongan stoknya apakah mau dari menu pengiriman barang atau dari menu sample?..
Jika mau langsung dari menu sample maka akan ditambahkan tombol "Kunci" untuk memotong stok..

mohon masukannya @sevenzk

**Comment by sevenzk** [comment]
Kunci aja kali? Tar PC lemot ga kuat angkat trus error. Lagipula itu akan kmungkinan di print jg klo itu brg sample.

**Comment by WinServer** [comment]
hmm..ya udah boleh sur..untuk reportnya sendiri formatnya apakah sama dengan pengiriman barang?..

**Comment by WinServer** [comment]
1. Format report untuk sample sama dengan report pengiriman barang (DO)
2. Untuk sample juga bisa retur dan retur dari Order Entry
3. Untuk sample harus ada harga supaya bisa retur (Ditambahkan di table baru sample)
4. Tombol kunci ada di menu sample tersendiri

**Comment by WinServer** [comment]
Untuk sample dan sponsor sudah diuji coba dari order entry diinput dengan nama pelanggan = sponsor..

Untuk barang hilang / losses sudah dites untuk stok gudang dan toko..sudah oke..
