### ISSUE TITLE
[POS] delete barang yg hadir di kombi

### ISSUE THREAD

**Issue by sevenzk** [sevenzk/SJKTCI#226]
Show warning untuk kalau mau delete barang, tapi barangnya ada di barang komposite.

Show barangnya hadir di komponen mana aja.

Atau cara ke2, mesti delete dl barangnya dari komponennya, baru bisa delete itu barang.

**Comment by fafn3r** [comment]
Jika barang satuan merupakan komponen, akan diberikan pesan bahwa barang tersebut merupakan komponen dari barang gabungan beserta daftar barang gabungan yang menggunakan komponen tersebut, kemudian harus menghapus barang tersebut dari gabungannya, baru bisa dihapus

**Comment by WinServer** [comment]
informasi untuk validasinya bisa diperjelas jangan seperti gambar di bawah:
![image](https://user-images.githubusercontent.com/44515909/64073769-83508e00-cccc-11e9-9c94-c022a28ae9f1.png)

**Comment by WinServer** [comment]
dan barangnya masih bisa kehapus..

**Comment by fafn3r** [comment]
mohon programnya diupdate, programnya baru dipush ke dropbox tgl 2 Sept jam 1.35AM

**Comment by WinServer** [comment]
sudah muncul validasi dan tidak terhapus..
