### ISSUE TITLE
[Search] Filter Pensiun

### ISSUE THREAD

**Issue by fafn3r** [sevenzk/SJKTCI#227]
mungkin tanggapan retired itu mesti di ubah
smua form yg bisa search barang
mesti ada filter buat pensiun

**Comment by WinServer** [comment]
Untuk menu Penyesuaian Stok, barang yg muncul adalah non retired..

Jika mau memunculkan barang retired ada flag untuk menampilkan barang retired..

**Comment by sevenzk** [comment]
ini kayanya sudah beres, di stok gudang dan toko perlu pensiun tapi sudah beres
