### ISSUE TITLE
[Ambil Order] Penambahan Flag di Grid sebelah kiri

### ISSUE THREAD

**Issue by WinServer** [sevenzk/SJKTCI#228]
Grid sebelah kiri pada menu Ambil Order berubah dengan adanya penambahan flag seperti gambar di bawah:
![image](https://user-images.githubusercontent.com/44515909/64073439-176c2680-ccc8-11e9-8cda-d0632978adc5.png)

Flag tersebut berfungsi untuk menandakan barang yang sudah selesai diambil akan segera dikirim.
Kondisi :
1. Jika barang sisa = 0 dan tekan tombol kirim tanpa ada flag yang tercentang maka yang dikirim ke konfirmasi adalah barang yang sisanya = 0
2. Jika tidak barang sisa yang bernilai 0 dan tekan tombol kirim tanpa ada flag yang tercentang maka tidak ada barang yang terkirim ke konfirmasi.
3. Jika ada barang sisa = 0 dan ada flag yang tercentang maka yang dikirim ke konfirmasi adalah barang yang sisanya bernilai 0 dan flag tersebut tercentang

**Comment by sevenzk** [comment]
Mantab, next development

**Comment by WinServer** [comment]
Pada saat klik tombol Kirim ke Konfirmasi dan tidak ada barang yang dicentang maka pesan yang muncul adalah "Barang tidak ada yang dikirim"..

**Comment by WinServer** [comment]
done dan okeh..
