### ISSUE TITLE
[Migrasi Data] Migrasi data PoS non PPn ke database terbaru

### ISSUE THREAD

**Issue by WinServer** [sevenzk/SJKTCI#230]
Akan dilakukan pemindahan database dari KTC ke SJKTCI untuk non ppn..

**Comment by sevenzk** [comment]
Mungkin untuk itu akan di masukkan manual data2nya. Biar start fresh

**Comment by WinServer** [comment]
akan diinput dan di akhir bulan akan dimasukkan nilai stoknya..
