### ISSUE TITLE
[SJKTCI Non Pajak] Ditambahkan menu Warehouse to Store

### ISSUE THREAD

**Issue by WinServer** [sevenzk/SJKTCI#233]
Menu WTH tetap diperlukan untuk mengakomodir barang yang sudah ada di gudang dan tidak ada barcode.

Untuk barang baru (yang akan datang) akan digunakan barcode baru..

**Comment by sevenzk** [comment]
pake penyesuaian stok saat ini. dan so far working fine. di pajak udah mulai dikit yg pake penyesuaian stoknya. jd keknya gua close dl aja.
