### ISSUE TITLE
[Barcode] Ada security barcode kedua

### ISSUE THREAD

**Issue by WinServer** [sevenzk/SJKTCI#239]

**Comment by sevenzk** [comment]
Apa ya ini?

**Comment by WinServer** [comment]
ini yg diomongin ko budi kemarin sur..yg katanya harus ada barcode kedua untuk jaga2 jika barcode pertama rusak..

**Comment by sevenzk** [comment]
yg penting tulis dl ya waakakakka

**Comment by sevenzk** [comment]
rip
