### ISSUE TITLE
[Master Promo dan Pesan Order] Ada promo barang

### ISSUE THREAD

**Issue by WinServer** [sevenzk/SJKTCI#240]
Ada kondisi promo barang dimana jika barang dibeli 50 maka ada bonus barang sebanyak 5.

Rencana untuk Flownya :
1. Ada penambahan menu Master Promo Barang di menu Master dengan pengisian sebagai berikut :
- Kode barang
- Nama Barang
- Jumlah barang yang dibeli
- Jumlah barang bonus
- Tanggal berlaku dari
- Tanggal berlaku sampai
Designnya adalah sebagai berikut :
![image](https://user-images.githubusercontent.com/44515909/65019409-569ba800-d955-11e9-8588-0408fa353cc7.png)

Untuk detilnya adalah sebagai berikut :
![image](https://user-images.githubusercontent.com/44515909/65019445-6915e180-d955-11e9-99be-f258e99a3c3e.png)

2. User menginput data di Pesan Order seperti biasa. Contoh : Barang A jika dibeli 10 maka akan ada bonus 1 barang. User menginput barang A sebanyak 50 maka ada barang A bonus sebanyak 5 dimana informasi Qty barang bonus ada di sebelah Qty Dipesan.

3. Pada saat Ambil Order, jumlah barang yang diambil adalah 55 (50 + 5 barang bonus) bukan 50 sehingga akan ada 55 barcode untuk barang A.

4. Pada saat konfirmasi, Jumlah barang A adalah sebanyak 55 namun pada saat penyimpanan data di table Sales Order akan muncul 2 baris dimana baris 1 berjumlah 50 dengan adanya nilai barang dan subtotal. Sedangkan untuk jumlah barang sisanya yang ke - 5 akan menambahkan row baru dengan harga adalah 0 dikarenakan 5 barang ini adalah bonus.

Ide untuk flow program:
1. Pada saat buat Pesan Order, akan ada informasi jumlah barang yang dibeli dan informasi jumlah bonus barang yang dihitung berdasarkan master barang promo (ada contoh tambahan field di order entry creation : Jumlah Barang, Bonus Barang, dan Total Barang)
2. Pada saat Ambil Order, Informasi Jumlah Barang, Bonus Barang, dan Total Barang akan terbawa ke Order_Entry_Preparation.
3. Pada saat scan barcode di konfirmasi maka system akan melihat jumlah barang yang di scan berdasarkan informasi jumlah barang. Jika sudah mencapai batas jumlah barang, maka system akan membuat row baru di tabel Sales_Order sebagai penanda bahwa barang tersebut adalah bonus dengan nilai barang adalah 0.

**Comment by WinServer** [comment]
mohon masukannya untuk issue ini sur.. @sevenzk

**Comment by WinServer** [comment]
Ada beberapa perubahan flow:

1. Pada menu Pesan Order, jika salah satu barang ada Qty Bonus maka informasi Qty Bonus baru muncul. Jika tidak ada yang mendapatkan Qty Bonus maka informasi Qty Bonus tidak akan muncul. 
Selain itu Qty Bonus baru akan dihitung pada saat klik tombol "Simpan".

2.  Pada saat export ke excel, konsepnya sama seperti point nomor 1.

3. Ada case dimana pada Pesan Order jumlah yang diisi adalah 50 dan jumlah bonusnya adalah 5. Pada saat dikirim ke ambil order dan mau dilakukan pengambilan barang baru diketahui bahwa stok barang tersebut cuma 30.
Pada saat pengiriman dari Konfirmasi akan dilakukan perhitungan kembali seperti excel berikut:
[Perhitungan Promo v0.1.xlsx](https://github.com/sevenzk/SJKTCI/files/5432427/Perhitungan.Promo.v0.1.xlsx)

4. Pada master promo, jika tanggal berlaku sampai sudah lewat maka sudah bisa diedit kembali.

**Comment by WinServer** [comment]
Kendala :

Ada case dimana pada Pesan Order jumlah yang diisi adalah 50 dan jumlah bonusnya adalah 5. Pada saat dikirim ke ambil order dan mau dilakukan pengambilan barang baru diketahui bahwa stok barang tersebut cuma 30.
Pada saat pengiriman dari Konfirmasi akan dilakukan perhitungan kembali seperti excel berikut:

Solusi :
1. Proses perhitungan ini akan dilakukan pada saat klik tombol kirim di Konfirmasi Order
2. Untuk penentuan barang bonus ada di koli mana dapat dilihat penentuannya di excel berikut:
[Perhitungan Promo v0.2.xlsx](https://github.com/sevenzk/SJKTCI/files/5504262/Perhitungan.Promo.v0.2.xlsx)

ada di sheet Hitungan Pintar

**Comment by fafn3r** [comment]
- sudah ditambahkan Master Promo, dan dibuat perubahan untuk mengakomodasi promo pada Buat Pesanan dan Konfirmasi Pesanan
- tagihan yang dicetak dipisah menjadi 2 versi, versi tanpa ongkos kirim jika subtotal ongkos kirim = 0 (barang/baris terakhir dari tagihan) dan versi dengan ongkos kirim jika subtotalnya > 0

**Comment by WinServer** [comment]
ada kondisi dimana barang yang berbeda namun satu induk yg sama bisa mendapatkan promo:
Contoh:
Barang ABCD (Parent) terdiri dari Barang A, B, C, dan D
Barang A, B, C, dan D merupakan child (barang satuan)

Barang ABCD (Parent) ada promo dimana jika beli 10 maka akan mendapatkan gratis 2..
contoh :
Ada penjualan Barang A : 4
Ada penjualan Barang B : 3
Ada penjualan Barang C : 5
Total : 12

Barang yang dijadikan bonus adalah barang yang terakhir (urutan terakhir) sehingga menjadi:
Yang kena harga:
Barang A : 4
Barang B : 3
Barang C : 3

Bonus :
Barang C : 2

Teknis:
- Secara teknis, system harus bisa membaca apakah barang ini mempunyai parent atau tidak
- Jika barang tersebut mempunyai parent, maka akan dicek kembali dalam satu order apakah ada yang mempunyai parent yang sama atau tidak
- Jika ada barang lain yang mempunyai parent yang sama maka jumlah barang akan dijadikan satu dan dihitung berdasarkan Master Promo.

Pertanyaan teknis:
Apakah perlu dibuatkan master promo induk atau tidak?..

**Comment by WinServer** [comment]
case terakhir tidak jadi diterapkan..
