### ISSUE TITLE
[Special Price] Harga barang spesial 

### ISSUE THREAD

**Issue by fafn3r** [sevenzk/SJKTCI#241]
Harga barang spesial yang tidak punya parent belum berfungsi
(case: Awi - PZ GN5 38)

**Comment by fafn3r** [comment]
Harga barang spesial sudah dibuat untuk mengakomodasi barang tanpa parent

**Comment by WinServer** [comment]
ada coba buat proses seperti berikut :
1. Mendaftarkan barang di special price untuk customer awi seperti gambar di bawah:
![image](https://user-images.githubusercontent.com/44515909/65746625-7f782600-e129-11e9-86b6-36c889473148.png)

2. Pembuatan pesan order di order entry untuk barang RC3-D sebanyak 10
3. Dikirim ke Ambil Order dan di scan 10 barcode
4. Dikirim ke Konfirmasi dan di scan 9 barcode
5. Dikirim ke PoS dan muncul di menu Pengiriman
6. Dikunci dan dikirim ke Tagihan Penjualan dengan tampilan sebagai berikut :
![image](https://user-images.githubusercontent.com/44515909/65746796-f1e90600-e129-11e9-8a1f-b8986007b928.png)

yang jadi pertanyaan adalah:
1. Harga yang masuk ke tagihan penjualan masih harga yang tercantum di master harga bukan di special price
2. Apakah ada kondisi harga special price akan terhitung pada saat kapan
3. Apakah jumlah minimum 0 mempengaruhi perhitungan harga special price

Coba dicek kembali, takutnya ada persepsi yang ane tidak tahu haha..

**Comment by WinServer** [comment]
Ternyata belum ambil program yang terupdate..sudah bisa dan sudah benar angkanya..
