### ISSUE TITLE
[Konfirmasi] Penambahan Tabel Barang Belum Diambil di Konfirmasi

### ISSUE THREAD

**Issue by fafn3r** [sevenzk/SJKTCI#242]
Ada permintaan dari pak kijan berupa:
- menambahkan tabel barang belum diambil di bagian konfirmasi
- peringatan ada barang belum dikerjakan/diambil ketika ingin kirim ke pos

**Comment by sevenzk** [comment]
Dibikin jadi konfirmasi aja, ampe 5x yg menjelaskan bahwa ada barang yg mau di eliminasi.

**Comment by WinServer** [comment]
Di grid sebelah kiri ditambahkan satu grid tambahan kecil di bagian kiri sebelah bawah yg berisi informasi barang yang belum dikirim ke konfirmasi seperti gambar di bawah:

![image](https://user-images.githubusercontent.com/44515909/74582055-41e93c00-4fe9-11ea-9069-491ba22c2f82.png)

**Comment by WinServer** [comment]
Sudah okeh untuk design ini, jika ada barang yang sudah discan di ambil maka informasi yang ada di konfirmasi juga sudah berkurang..
