### ISSUE TITLE
[Item Barcode Generator] Proteksi

### ISSUE THREAD

**Issue by WinServer** [sevenzk/SJKTCI#250]
Ditambahkan proteksi untuk sisa barcode sehingga tidak ada barcode yang terbuang.

Flow kejadian pertama adalah :
1. Barang A di toko mempunyai sisa stok 500
2. Di aplikasi generate barcode, dibuat 200 barcode untuk Barang A sehingga ada sisa 300 barcode untuk Barang A (300 = 500 - 200)
3. Sisa barcode akan terhitung ketika klik tombol excel
4. Cetak barcode untuk Barang A berikutnya hanya sebesar 300 atau sisa barcode dan tidak bisa lebih.
5. Jika ditulis cetak barcode > 300 maka ada validasi "Barcode tidak bisa dicetak lebih dari 300  (sisa) barcode"

Flow kejadian kedua adalah :
1. Ada pembelian Barang A sebanyak 100 dimana sisa barang adalah 400 dan sisa barcode adalah 300
2. Dengan adanya pembelian Barang A maka sisa barang di toko adalah 400 dan sisa barcode adalah 300 =>  ini kondisi jika belum dipindah dari gudang ke toko
3. Barang A dipindah dari gudang ke toko sebanyak 100 maka sisa barang di toko adalah 500 dan sisa barcode yang bisa dicetak adalah 400

Penambahan informasi sisa barcode di master_item_single (field) untuk menampung sisa barcode

**Comment by sevenzk** [comment]
kenyataanya karyawan suka seenak jidat, perlu di perhatiin lagi sih ini dari SOP nya
