### ISSUE TITLE
[Master Harga] Harga Level 4

### ISSUE THREAD

**Issue by fafn3r** [sevenzk/SJKTCI#252]
Sudah boleh dihapus untuk pajak dan non pajak

**Comment by fafn3r** [comment]
Sempat diinformasikan untuk dibiarkan dulu

**Comment by WinServer** [comment]
menurut saya dibiarkan saja dulu..paling di nol kan saja untuk harga level 4..

**Comment by WinServer** [comment]
di remove ya untuk task ini dikarenakan sepertinya masih diperlukan dengan adanya harga level 5.
