### ISSUE TITLE
[SJMPOS] Klasifikasi

### ISSUE THREAD

**Issue by sevenzk** [sevenzk/SJKTCI#255]
Cepat atau lambat itu mesti ke barang yg mau dijual, jadi kalau ditaro di barang satuan, kayanya kurang sip penempatannya, item yg ada harga yg perlu itu, sama dengan berat barang juga, harusnya ke barang yg ingin dijual.

**Comment by sevenzk** [comment]
Gua ganti dia jadi high karna mau masukin ke price list juga supaya para distributor barang apa yg mesti mereka ambil stiap bulannya

**Comment by WinServer** [comment]
Ditambahkan field klasifikasi pada tabel Master_Category dengan tujuan untuk mencatat klasifikasi barang tersebut masuk dalam slow moving dan fast moving.

Untuk klasifikasi ini akan dicatat untuk barang satuan dan gabungan.

**Comment by fafn3r** [comment]
Untuk sementara, penentuan klasifikasi dilakukan di form master item satuan dan gabungan, ditampilkan daftar lengkapnya pada master katalog
Untuk didiskusikan lebih lanjut apakah penentuan klasifikasi mau dipindah ke master katalog

**Comment by WinServer** [comment]
Untuk Master Barang Satuan, pada saat centang klasifikasi lambat maka klasifikasi cepat akan hilang flagnya..Begitupun sebaliknya..

**Comment by WinServer** [comment]
okehh..sudah fixed..
