### ISSUE TITLE
[SJMPOS & SJKTCI kayanya] Master Item Barang Satuan

### ISSUE THREAD

**Issue by sevenzk** [sevenzk/SJKTCI#256]
![image](https://user-images.githubusercontent.com/14845394/66126741-561d3580-e614-11e9-8bfd-f773be1ddaed.png)

Ngebug pas mau retire dan ga ada row lagi, workaroundnya di show retired dl. Low prio.

**Comment by WinServer** [comment]
sudah tidak ada error spt itu lagi..boleh di push..
