### ISSUE TITLE
[SJMPOS] Pesanan

### ISSUE THREAD

**Issue by sevenzk** [sevenzk/SJKTCI#258]
![image](https://user-images.githubusercontent.com/14845394/66184523-9dec9d00-e6a6-11e9-99df-2e91d44f77b7.png)

kena bug ini abis ngirim.

**Comment by WinServer** [comment]
Muncul error ketika klik kirim seperti gambar di bawah:
![image](https://user-images.githubusercontent.com/44515909/75601441-c5c51d00-5aed-11ea-9bf2-74c97abb477d.png)

**Comment by WinServer** [comment]
sudah okeh..done..
