### ISSUE TITLE
[Master Pengaturan] Ditambahkan informasi pemilihan pajak dan icon

### ISSUE THREAD

**Issue by WinServer** [sevenzk/SJKTCI#260]
Pada master pengaturan ditambahkan informasi perhitungan pajak seperti gambar di bawah :
![image](https://user-images.githubusercontent.com/44515909/66249653-0009d880-e761-11e9-9289-2998aceb4368.png)

Selain perhitungan pajak, ditambahkan lokasi icon untuk ditandakan mau menggunakan icon yang mana.

**Comment by sevenzk** [comment]
udah ga inget lagi ini yg mana
