### ISSUE TITLE
Master Parent Item Single & Master Harga

### ISSUE THREAD

**Issue by sevenzk** [sevenzk/SJKTCI#261]
![image](https://user-images.githubusercontent.com/14845394/66281136-2dcb5a80-e8e4-11e9-973c-ab1410f9e4d1.png)

Saat menginput Master Parent Item Single, item pertama dipencet YA untuk mengikuti harga parentnya, yg terjadi adalah Parent yg mengikuti harga Single.

Yg ke 2 saat menginput item ke 2 dipencet Tidak harga menjadi 0

![image](https://user-images.githubusercontent.com/14845394/66281191-62d7ad00-e8e4-11e9-9dd6-e564600a0a52.png)

**Comment by fafn3r** [comment]
Diperbaiki dan dimodifikasi menjadi peringatan ketika ingin menambahkan barang turunan ke dalam induk

**Comment by WinServer** [comment]
- Harga yang muncul masih 0 jika input master induk barang satuan baru (parent & child)..
- Pada saat dihapus child terakhir, parentnya tidak terhapus
- Pada saat update harga di parent, muncul notifikasi "divide zero" namun mengupdate harga di child nya

**Comment by sevenzk** [comment]
ini udah pushed, sudah fixed @WinServer ?

**Comment by WinServer** [comment]
yg ini sepertinya masih ada bugs pada saat :
1. Buat master item single baru (sebagai child)
- CHD01 = Child 1
- CHD02 = Child 2
- CHD03 = Child 3

2. Masukkan harga ke ke master harga pada master item single baru (Child 1)

3. Membuat parent baru dengan mengambil child1 untuk pertama kali. yg masalah adalah harga pada parent dan Child 1 menjadi 0 dimana seharusnya parent mengambil harga dari child 1, baru kemudian child 2 dan 3 mengambil dari parent.

Mohon koreksi jika ada salah...

**Comment by WinServer** [comment]
sudah benar untuk proses perhitungannya..
