### ISSUE TITLE
[Pengiriman Barang] Stok Barang Gabungan

### ISSUE THREAD

**Issue by fafn3r** [sevenzk/SJKTCI#263]
Penjualan barang gabungan hanya memperbarui qty gabungannya sendiri dan komponen gabungan tersebut tanpa memperbarui gabungan lainnya yang menggunakan komponen yang sama

**Comment by fafn3r** [comment]
Refer to #205

**Comment by sevenzk** [comment]
ini gmn nih? critical apa medium? kayanya stok sih aman, tapi data jumlah gabungannya ya yg ga bener?

**Comment by WinServer** [comment]
sudah okeh karena yg 205 sudah dites dan dicoba..
