### ISSUE TITLE
[Penyesuaian stok] bisa edit tanggal

### ISSUE THREAD

**Issue by sevenzk** [sevenzk/SJKTCI#266]
Sampai bisa warehouse to store, kayanya ini di perlukan. Kecuali warehouse to store bisa dibuat dalam bulan depan.

**Comment by fafn3r** [comment]
sudah ditambahkan fitur edit (tanggal, tipe stok, dan perubahan qtynya) dan delete

**Comment by WinServer** [comment]
Tanggal sudah ditambahkan dan sudah bisa diedit..untuk stok juga sudah mengikuti dimana jika ada perubahan dari toko ke gudang maka stok toko akan dikurangi / ditambahkan terlebih dahulu baru mengurangi atau menambahkan stok gudang..
