### ISSUE TITLE
[Barang Satuan]

### ISSUE THREAD

**Issue by sevenzk** [sevenzk/SJKTCI#267]
![image](https://user-images.githubusercontent.com/14845394/66740319-0e609e80-ee9d-11e9-92b3-f49431801598.png)

Mungkin disini kalo dia part of barang gabungan, trus diganti namanya mungkin ada notif untuk update nama barangnya ke dalem bagian dari barang gabungan?

"Apakah anda mau meng update nama barangnya ke barang gabungan?"

Atau mending tanpa notif lgs update nama barangnya ke bagian dari nama gabungan?

**Comment by sevenzk** [comment]
ke gabungan dan parent
pesanan dan tagihan
spesial

dan dimana lagi ya yg bakal ke affect?

**Comment by WinServer** [comment]
refer to issue #10
