### ISSUE TITLE
[SJMPOS & SJKTCI] Shipping datang berbarengan

### ISSUE THREAD

**Issue by WinServer** [sevenzk/SJKTCI#274]
Ada case dimana shipping datang berbarengan (gabungan dari beberapa invoice) dan baru bisa dihitung untuk HPP dikarenakan nilai ongkos kirim dan bea masuknya dijadikan satu.

**Comment by sevenzk** [comment]
blkgan ini udah rapi, tidak ada yg berbarengan lagi
