### ISSUE TITLE
[Pembayaran] Dibuatkan shortcut untuk tombol simpan dan selesai

### ISSUE THREAD

**Issue by WinServer** [sevenzk/SJKTCI#282]
Pada tombol simpan dibuatkan shorcut F2
Pada tombol selesai dibuat shortcut F3

**Comment by fafn3r** [comment]
F3 sudah dipakai untuk simpan, karena F2 biasanya dipakai untuk "Cari", maka tombol selesai diberikan pintasan F4

**Comment by WinServer** [comment]
ada muncul error ketika klik tombol selesai seperti gambar di bawah:
![image](https://user-images.githubusercontent.com/44515909/74217093-16a8d900-4cd9-11ea-8be0-4ae940018d5e.png)

**Comment by WinServer** [comment]
sudah diset menjadi default per tanggal tagihan..
