### ISSUE TITLE
[Master Barang Satuan] di SJKTCI & SJMPOS stiap ada barang baru stok opnamenya di centang

### ISSUE THREAD

**Issue by sevenzk** [sevenzk/SJKTCI#291]
Topic.

Biar kalo lg cek tau apa yg belom ke opnam.

**Comment by WinServer** [comment]
Centangan Stock Opname dipindahkan ke Penyesuaian Stok..
Untuk saat ini, barang baru pada saat didaftarkan pertama kali sudah langsung tercentang untuk stock opname di Penyesuaian Stok..
Jika di klik tombol Stock Opname maka akan dilakukan uncheck / check pada data Stock Opname..

Ada tambahan untuk Uncheck All, tidak ada untuk Check All..

Refer to issue #292
