### ISSUE TITLE
[ORDER ENTRY - PESAN] perlu ada total harga dibawah atau dimana biar bisa liat total orderan

### ISSUE THREAD

**Issue by sevenzk** [sevenzk/SJKTCI#294]
dikarenakan kita sudah mulai kasih banhammer ke distributor yg bayarnya lama, jadi mungkin di pesan, adminnya bisa lbh mudah untuk ngelimit barang apa yg ingin dikasih ke customer tersebut.

Issue lainnya kmrn si Triska order ampe 400jt, kaget jg, alangkah baiknya klo dilimit skali pembelian ga lebay gitu sih.

**Comment by WinServer** [comment]
Done...perhitungannya sudah benar..
