### ISSUE TITLE
[Master Setting & Master Harga] Untuk DPP akan dibulatkan 1000 ke atas jika master setting berubah

### ISSUE THREAD

**Issue by WinServer** [sevenzk/SJKTCI#30]
1. Edit kurs di master setting (simpan dan perbaharui)
2. Angka DPP di master harga (level 1,2,2.5,3, dan store) dibulatkan 1000 ke atas
3. Untuk Harga jual tetap 10% x DPP

**Comment by fafn3r** [comment]
fixed

**Comment by fafn3r** [comment]
Pindah ke #35
