### ISSUE TITLE
[Konfirmasi] Penambahan Kolom Stok Toko

### ISSUE THREAD

**Issue by fafn3r** [sevenzk/SJKTCI#300]
Ada permintaan dari pak Kijan untuk bisa melihat stok toko pada pesanan (Pesan/Konfirmasi)

**Comment by fafn3r** [comment]
Sudah ditambahkan stok toko pada tabel pesanan yang belum dikerjakan.

**Comment by WinServer** [comment]
sisa stok sudah muncul di konfirmasi..
