### ISSUE TITLE
[Penagihan] Penambahan informasi diskon

### ISSUE THREAD

**Issue by WinServer** [sevenzk/SJKTCI#307]
Pada menu penagihan ada penambahan informasi diskon seperi gambar berikut:
![image](https://user-images.githubusercontent.com/44515909/84557885-f3f70180-ad58-11ea-9503-002821eb558a.png)

Sedangkan di bagian detil barang ditambahkan informasi diskon seperti gambar berikut:
![image](https://user-images.githubusercontent.com/44515909/84558013-c9597880-ad59-11ea-9bc0-1a059f6182b5.png)

Penjelasan:
1. Informasi diskon yang ditambahkan adalah diskon (%) dan diskon (Rp) pada masing-masing barang
2. Rumusan subtotal masing-masing barang berubah menjadi : (Harga - (Harga - Diskon (Rp))) * Jumlah Barang
3. Ditambahkan juga tombol **ubah** pada bagian kanan atas untuk mengubah angka diskon (%) / (Rp) dan tombol **Diskon Semua Barang** dengan tujuan membuat semua barang menjadi diskon yang sama.
4. Informasi diskon di bagian bawah dihilangkan dikarenakan sudah ada diskon satuan untuk masing-masing barang sehingga nilai subtotal sudah termasuk diskon.

**Comment by sevenzk** [comment]
Kode ga usah sih bung di bon.

Harga dan diskon ga perlu ditulis "satuan" ga yah?

**Comment by WinServer** [comment]
Yg dibawah itu bukan untuk bon sur tapi untuk detil barang di menu penagihan..

Untuk bon tetap sama seperti kemarin sur formatnya..

**Comment by sevenzk** [comment]
oww woke, boleh lanjut klo gt.

**Comment by WinServer** [comment]
1. jika tombol ubah di sebelah kanan atas di klik maka textboxt harga, diskon%, dan diskon Rp akan bisa diedit.
2. Ketika textbox harga diedit, setelah selesai diedit maka akan muncul pop up untuk mengisi password admin
3. Di sebelah kanan atas ditambahkan tombol Simpan dan Batal
4. Pada saat klik tombol diskon semua barang, akan muncul pop up untuk mengisi nilai diskon % saja

**Comment by WinServer** [comment]
masih ada sedikit bugs pada saat penginputan diskon melebih harga aslinya..akan segera diperbaiki..

**Comment by WinServer** [comment]
sudah diperbaiki dan sudah bisa di push..
