### ISSUE TITLE
[Master Barang Satuan] Chinese languange enable di bagian pemasok

### ISSUE THREAD

**Issue by WinServer** [sevenzk/SJKTCI#32]

**Comment by fafn3r** [comment]
nvarchar enabled di:
- Master Item Single: Item Name, Supplier 1, Supplier 2, Supplier Item Name 1, Supplier Item Name 2
- Master Parent Item Single: Parent Name, Child Name
- Master Item Composite: Composite Name, Component Name
- Master Item No Quantity: Item Name
- Master Supplier: Supplier Code, Supplier Name, Address, City, Country, Contact Person, Note
- Master Price: Item Name
- Packing List: Supplier Name
- Barcode List: Supplier Name
- Goods Received: Supplier Name
