### ISSUE TITLE
[Pengiriman Barang] Saat ini bisa di klik 2x berbarengan dan terpotong 2x

### ISSUE THREAD

**Issue by WinServer** [sevenzk/SJKTCI#325]
Proses Kerja:
1. User A dan User B klik kunci pada pengiriman barang secara berbarengan.
2. Stok pada barang terpotong sebanyak 2x.

Solusi :
1. Apakah memungkinkan dibuatkan proses antrian dan dibuatkan pengecekan apakah sudah dikunci atau belum.
2. Jika sudah dikunci maka User A atau User B akan mendapatkan notifikasi bahwa tidak bisa melakukan penguncian.

**Comment by fafn3r** [comment]
sudah diperbaiki

**Comment by WinServer** [comment]
sudah beres dan belum ada masalah sampai saat ini..
