### ISSUE TITLE
Ada Perubahan untuk Program SPoS

### ISSUE THREAD

**Issue by WinServer** [sevenzk/SJKTCI#327]
Pada saat pengisian baru dan ubah nama dan nama tersebut sudah digunakan oleh barang lain maka akan muncul validasi **"Nama Barang sudah digunakan"**..

**Comment by WinServer** [comment]
Untuk flow di SPoS rencananya menjadi :
Pembelian => Scan Barcode untuk Masuk ke Toko => Penjualan

**Data master yang diperlukan:**
- Master Barang Satuan
- Master Barang Gabungan
- Master Harga
- Master Pemasok
- Master Pelanggan
- Master Harga Spesial

**Proses Pembelian:**
Bukan Drop Shipper
- Input barang di menu Pembelian dan klik tombol kirim untuk dikirim ke Pesanan di SJKTCI dan SJMPOS
Syarat : Barang harus dipisahkan antara Barang Pajak dan Non Pajak sehingga pada saat dikirim akan dipisahkan barang mana yang masuk ke Pesanan Pajak dan Pesanan Non Pajak

- Setelah klik kirim, maka order entry SJKTCI dan SJMPOS akan menerjemahkan kode barang yang dikirim dari SPoS menjadi barang pesanan di order entry SJKTCI dan SJMPOS dengan status draft.

- Barang datang dan akan di scan barcode dengan menu "Barang Masuk ke Toko" seperti gambar berikut:
![image](https://user-images.githubusercontent.com/44515909/101234544-de083f00-36f2-11eb-8889-9e38d49a415b.png)

- Pada saat scan barcode, di sebelah kiri akan muncul barcode barang.
- Di sebelah kanan akan terakumulasi dari barcode sebelah kiri
Contoh :
    - Di Sebelah kiri akan muncul barcode BKX6320M00001, BKX6320M00002, BKX6320M00003, dan BKX6320M00004
    - Di Sebelah kanan akan muncul barang BLOK KLX150 BIASA SET BLK-14 63MM dengan total barang = 4
Teknis :
    - Secara database akan dipisah menjadi 2 table dimana 1 table untuk menyimpan barcode number pembelian disertai dengan nomor GR dan 1 table untuk menyimpan data total barang dengan nomor GR yang sama.
   - Contoh :
         - Jika ada scan barcode hari ini maka nomor GR yang terbentuk adalah GR-20201205

- Barcode barang satuan dari toko belakang akan sama dengan barcode masuk di toko depan
- Barang yang masuk ke toko depan akan masuk sebagai barang satuan (berlaku untuk barang gabungan dari toko belakang)

Untuk Drop Shipper
- Barang yang dikeluarkan dari toko belakang akan langsung masuk ke toko depan untuk dicatat sebagai stock dan langsung masuk ke data penjualan mereka untuk dilakukan print oleh toko depan

**Proses Penjualan:**
- Akan dilakukan scan barcode untuk penjualan barang
- Flow scan barcode sama persis dengan flow konfirmasi di order entry dimana pada saat scan barcode maka akan langsung menggenerate menjadi barang penjualan
- Informasi barcode tetap tersimpan di dalam database sehingga pada saat scan ada 2 tabel yang diupdate (Penyimpanan Barcode dan Penjualan)

**Comment by WinServer** [comment]
Tampilan, susunan database, dan konsep untuk Master Barang Satuan, Master Barang Gabungan, Master Pelanggan, Master Pemasok, dan Harga Spesial sama dengan PoS SJKTCI..

Sedangkan untuk master harga, yang ditampilkan adalah sebagai berikut:
![image](https://user-images.githubusercontent.com/44515909/100568643-52f80500-32fe-11eb-872f-267b840358c2.png)
Harga HET (Sebelum Pajak) dirubah menjadi "Harga Jual" dan Harga Jual Tertinggi (sesudah pajak) dirubah menjadi Harga Jual 

Untuk grid index detil harga, informasi yang dimunculkan adalah:
- Kode Barang
- Nama Barang
- Tipe Barang
- Harga Jual

**Comment by WinServer** [comment]
- Untuk Master Harga ada perubahan dimana akan harga yang dibutuhkan ada 3 level (Harga level 1, 2, dan 3)..
- Untuk Master Pelanggan ada penambahan dimana nama pelanggan "Cash" diperuntukkan pelanggan luar yang bukan distributor..

**Comment by WinServer** [comment]
Untuk proses penjualan,  ada perubahan proses dimana:
1. Pada saat scan barcode, maka akan dihitung untuk harga penjualannya (harga yang diambil dari master harga adalah harga setelah pajak untuk barang tersebut).
2. Nilai penjualan (harga) yang muncul setelah selesai di scan adalah harga setelah pajak dan baru dihitung ke harga sebelum pajak beserta nilai PPN nya.

untuk Master Harga ada perubahan dimana;
1. Untuk harga jual ada SW, RS, dan HET. Untuk harga W tidak ada / tidak muncul.
2. Harga beli dalam hal ini tidak ada hubungannya dengan harga jual barang.

Untuk Retur, Formnya akan sama seperti barang masuk dengan ketentuan:
1. Table akan dipisah untuk barang yang diretur dan barang yang akan diganti.
2. Tampilan dibagi menjadi 3 grid dengan adanya 1 grid di sebelah kiri dan 2 grid di sebelah kanan.
3. Grid kanan atas berisi barang yang diretur, sedangkan Grid kanan bawah berisi barang yang ditukar.
4. Retur tidak berlaku untuk barang yang tanpa kemasan sehingga tidak terima retur yang tidak mempunyai barcode.

**Comment by WinServer** [comment]
Untuk penjualan ada hal yang harus diperhatikan yaitu:
1. Pada saat barang gabungan dijual dan di scan maka barcode anak dari barang gabungan tersebut akan tercatat juga sehingga pada saat retur barcode tersebut akan tercatat.
2. Dari point nomor 1, maka dibutuhkan Master Paket Gabungan untuk mendaftarkan Barcode Utama dan Barcode Anaknya.

**Comment by fafn3r** [comment]
Program SPoS yang baru sudah dibuat dan sudah dipush
