### ISSUE TITLE
[Master Paket Barcode] Ditambahkan fitur untuk search untuk mencari data

### ISSUE THREAD

**Issue by WinServer** [sevenzk/SJKTCI#330]
Kondisi :
Ada user yang mau melihat paket ini mempunyai barcode apa saja (list barcode) dan saat ini belum bisa dicari secara mandiri oleh user

Task :
Ditambahkan **Fitur Search** untuk memudahkan user mencari paket barcode tersebut mempunyai komponen barcode apa saja
![image](https://user-images.githubusercontent.com/44515909/99025751-21600980-259c-11eb-9cb6-cb48a4d66c47.png)

**Comment by sevenzk** [comment]
Gimana kalo master paketnya buat bikin paket aja, utk history kaya SS diatas dibikinin historynya.

Jd workflow yg udah ada ga diganti, tp utk liat paket dgn komponennya di history?

**Comment by fafn3r** [comment]
sudah diubah sehingga hanya menampilkan barcode paket yang belum digunakan saat scan, tidak lagi menampilkan semua barcode paket yang belum digunakan ketika membuka Master Paket Barcode

**Comment by WinServer** [comment]
Done dan sudah diimplementasikan dan tidak ada kendala sampai saat ini..
