### ISSUE TITLE
Proses Marketplace yang di handle showroom / Toko Depan

### ISSUE THREAD

**Issue by WinServer** [sevenzk/SJKTCI#335]
**Kendala:**
1. Stok Marketplace hari ini tidak terkontrol
2. Penjualan Marketplace dihandle oleh toko depan namun stoknya diambil dari toko belakang
3. Bon juga berasal dari toko belakang
4. Stok depan menjadi berantakan dikarenakan seringkali lupa mengambil stok dari toko belakang

**Solusi :**
1. Dibuatkan Program Baru untuk Marketplace namun database dijadikan satu dengan SJKTCI

**Proses Pengambilan Barang:**
1. Untuk user Marketplace akan mengajukan request barang pada menu "Pembelian" dan sub menu "Pengambilan Barang" dengan isi dari menu tersebut adalah:
![image](https://user-images.githubusercontent.com/44515909/102680497-378c6580-41eb-11eb-9dc4-1a4bafaa4e2d.png)
- Detil Informasi barang adalah seperti gambar berikut:
![image](https://user-images.githubusercontent.com/44515909/102680465-07dd5d80-41eb-11eb-8fc0-a4cde12f31aa.png)

2. Ada tombol "Kirim" yang bertujuan untuk mengirimkan informasi ke user SJKTCI (masuk ke order Entry dengan nama pelanggan adalah "Marketplace")

3. User SJKTCI akan melakukan proses Ambil Order, Konfirmasi Order, dan melakukan proses pengiriman dimana datanya akan masuk ke menu "Marketplace" seperti gambar berikut: 
![image](https://user-images.githubusercontent.com/44515909/102680642-b03ff180-41ec-11eb-9c8f-ab64910927e4.png)

4. Pada menu Marketplace berisikan informasi seperti gambar berikut:
![image](https://user-images.githubusercontent.com/44515909/103628435-984cc980-4f71-11eb-9fa7-c7aa779a9b5b.png)

5. Untuk detilnya adalah seperti gambar berikut:
![image](https://user-images.githubusercontent.com/44515909/103628585-d34efd00-4f71-11eb-95c6-c06283617de0.png)

6. Setelah klik **"Kunci"**, maka qty di stok toko SJKTCI akan terpotong.

**Comment by sevenzk** [comment]
Stelah nomor 3, ada baiknya barangnya pindah ke stok marketplace sendiri
TOKOPEDIA OFFICIAL
BUKALAPAK OFFICIAL
SHOPEE OFFICIAL

masing2 punya stok sendiri.

Nah stelah ini, tinggal bikin bon seperti di SPOS yg langsung scan barangnya dan bikin detilnya sperti di Step 5?

Step 4 gua aga lupa utk apa yah?

**Comment by WinServer** [comment]
Step 4 itu istilahnya sama seperti menu Pengiriman Barang untuk memotong stocknya..

**Comment by WinServer** [comment]
Untuk hal ini alurnya menjadi:

User Marketplace buat pesanan untuk mengisi stok marketplace => Masuk ke Pesan Order => Melakukan Ambil Order => Melakukan Konfirmasi Order => masuk ke menu stok dan Marketplace => klik tombol Kirim dan akan memotong stok toko dan menambah stok marketplace => masuk ke menu Penjualan Marketplace => Proses penjualan sama seperti SPoS yang sekarang

Note :
- Proses Penjualan Marketplace adalah scan barcode dan masuk ke tagihan. Secara table akan ditambahkan 1 table untuk menampung barcode Penjualan Marketplace.

- Untuk hal ini, aplikasi Marketplace akan dibuat terpisah dengan aplikasi SKI dikarenakan user yg pegang berbeda dengan user SKI. Aplikasi Marketplace berisi menu :
      - Pesanan Marketplace
      - Stok Marketplace
      - Penjualan Marketplace

- Perlu ada fitur print tagihan di aplikasi Marketplace di menu Penjualan Marketplace

- Informasi menu Penjualan Marketplace sama seperti menu Penjualan SPoS. Data yang muncul di Penjualan Marketplace difilter berdasarkan Master Pelanggan yang mempunyai flag Marketplace

- Untuk Master Pelanggan ditambahkan flag Marketplace Pembelian dan Marketplace Penjualan

- Untuk Pesanan Marketplace konsepnya sama seperti Pesanan Pembelian di SPoS

**Comment by fafn3r** [comment]
Program Marketplace sudah dibuat dan sudah dipush

**Comment by WinServer** [comment]
Sudah diimplemantasikan untuk modul ini..
