### ISSUE TITLE
Minor Fixing here and there.

### ISSUE THREAD

**Issue by sevenzk** [sevenzk/SJKTCI#336]
- Pas export Riwayat Penjualan, ONGKOS KIRIM ikut ke export, bisa ga kliatan kalo ongkirnya 0? [SJM & SJKTCI]
- Master Gabungan > Ubah barcode > Bisa di save kalo barcodenya menjadi 4 alphanumeric utk Kode Gabungan nya.

**Comment by fafn3r** [comment]
- Riwayat penjualan dipaksa tampilkan hanya barang yang harga > 0
- fixed

**Comment by WinServer** [comment]
untuk barang bonus tetap harus ditampilkan walaupun nilainya 0 dan untuk ongkos kirim yang nilainya > 0 tetap dimunculkan.. Query yang digunakan adalah:
select Sales_Order_Date,Sales_Order_Number,Item_Code,Item_Name ,Price
from Sales_Order
where (Price = 0 and item_name <> 'ONGKOS KIRIM')
or Price > 0 
order by Sales_Order_Date desc

**Comment by WinServer** [comment]
untuk barang bonus yg nilai 0 sudah muncul dan ongkos kirim yang > 0 juga sudah muncul di riwayat penjualan..
