### ISSUE TITLE
[SJM & SKI] Riwayat Penjualan

### ISSUE THREAD

**Issue by sevenzk** [sevenzk/SJKTCI#341]
Saat ini riwayat penjualan dipakenya utk para sales/finance. Form ini bisa jg dipake buat org produksi utk belajar forecast dan nge cek riwayat penjualan mereka.

![image](https://user-images.githubusercontent.com/14845394/108304941-a120f400-71db-11eb-8209-77c0fba11d1f.png)

Yg perlu mereka liat kalau di bagian barang, kurang lebih sperti ini. Dan bisa mereka export excel utk cek total jumlah barangnya.

**Comment by fafn3r** [comment]
sudah dibuat di riwayat pada order entry

**Comment by WinServer** [comment]
sudah oke dan sudah digunakan..
