### ISSUE TITLE
[SJM & SKI] Format zoho

### ISSUE THREAD

**Issue by sevenzk** [sevenzk/SJKTCI#342]
sudah di dropbox

**Comment by sevenzk** [comment]
![image](https://user-images.githubusercontent.com/14845394/109487365-b426a480-7ab6-11eb-93c4-dfbded690ca9.png)

untuk para distributor, field ini tulisannya ini. (basically untuk kapan ditagihnya)

Untuk org laennya, Due on Receipt

![image](https://user-images.githubusercontent.com/14845394/109487506-dddfcb80-7ab6-11eb-861f-7b74adb5798b.png)

Apa mungkin ini perlu field baru buat pelanggan?

**Comment by sevenzk** [comment]
ini kayanya udah beres? paling gua mesti cari tau kalau ada brg yg jualannya ke duplikat, itu gua aga bingung aja

contoh kartu 3 ama karton 4 sama2 item namanya sama. kalo di zoho ga ngerti gituan, dia bakal merge. coba nanti di zoho gua buat, trus gua export, liat mereka cara exportnya kaya gimana.

**Comment by WinServer** [comment]
udah beres
