### ISSUE TITLE
[SPoS] Buat Bon untuk SPoS terbaru

### ISSUE THREAD

**Issue by WinServer** [sevenzk/SJKTCI#343]
untuk SPoS terbaru dibuatkan bon terbaru dimana untuk datanya akan dibuat group by sehingga di bon hanya akan muncul satu barang barang untuk qty > 1

**Comment by fafn3r** [comment]
Sudah dibuat pada Pesanan Penjualan dan Riwayat Penjualan

**Comment by WinServer** [comment]
sudah dibuat dan sudah digunakan ditoko depan..
