### ISSUE TITLE
[SPoS Penjualan] bisa mengembalikan penjualan dan bisa dihapus

### ISSUE THREAD

**Issue by WinServer** [sevenzk/SJKTCI#344]
Jika sudah klik tombol kirim dan ada kesalahan maka transaksi tersebut bisa dikembalikan dan bisa dihapus untuk barcode barang yang sudah di scan.

yang harus berubah:
- Nilai penjualan (subtotal, total after discount, total after tax, dan total sales) berubah
- Stok dikembalikan  / ditambah 1 berdasarkan jumlah barcode yang dihapus

**Comment by fafn3r** [comment]
sudah ditambahkan tombol untuk mengembalikan pesanan dari riwayat penjualan ke pesanan penjualan
perubahan pesanan dilakukan di pesanan penjualan seperti kondisi sebelum pesanan diselesaikan (dikirim ke riwayat penjualan)

**Comment by WinServer** [comment]
proses pengembalian sudah bisa dilakukan dari riwayat ke pesanan penjualan dan bisa dilakukan perubahan untuk nomor penjualan tersebut.
