### ISSUE TITLE
[SPoS Master Barang Satuan] Ubah kode barang berpengaruh terhadap informasi lainnya

### ISSUE THREAD

**Issue by WinServer** [sevenzk/SJKTCI#345]
Jika ada perubahan kode barang dan nama barang maka akan ada perubahan di informasi lainnya seperti :
- Pesanan Pembelian (Purchase Order)
- Barang Masuk (Goods Received)
- Pajangan (Display)
- Penjualan (Sales Order)
- Retur (Sales Return)

**Comment by fafn3r** [comment]
juga ditambahkan untuk master barang gabungan

**Comment by fafn3r** [comment]
berdasarkan diskusi tgl 18 sore di discord, perubahan kode/nama barang akan dicegah jika sudah ada pesanan pembelian (untuk barang satuan) atau terjual/digunakan sebagai pajangan (untuk barang kombinasi)

**Comment by WinServer** [comment]
sudah digunakan dan diterapkan.
