### ISSUE TITLE
[Purchase Request] Ditambahkan form PR untuk request barang

### ISSUE THREAD

**Issue by WinServer** [sevenzk/SJKTCI#349]
Ada 2 pilihan untuk Form Purchase Request (dikarenakan akan dibuat di PoS dan Order Entry):

**Pilihan Pertama:**
Form headernya adalah sebagai berikut:
![image](https://user-images.githubusercontent.com/44515909/127846989-9970d9f8-ddfd-47b5-abae-de2cac60cd75.png)

Informasi Detil Permintaan adalah sebagai berikut:
![image](https://user-images.githubusercontent.com/44515909/127848293-5e483ba9-bd0c-4fb8-a776-ced26d1aee29.png)

Informasi Detil Barang Permintaan adalah sebagai berikut:
![image](https://user-images.githubusercontent.com/44515909/127848538-5dfeb708-157a-4a3d-9be1-cf0c42d05636.png)

**Pilihan Kedua:**
Form Headernya adalah sebagai berikut:
![image](https://user-images.githubusercontent.com/44515909/127848653-ec390199-ca61-48fe-a4ac-7048af60cac1.png)

Informasi Detil Permintaan adalah sebagai berikut:
![image](https://user-images.githubusercontent.com/44515909/127848990-7e9cd51c-6386-414a-8ed8-40c9833be4aa.png)

Silahkan dipilih mana yang lebih baik dan mudah antara Pilihan Pertama dan Kedua.

**Informasi Database:**
Nama Table : Purchase_Request

Nama Field :
- Purchase_Request_Date
- Purchase_Request_Number
- Purchase_Order_Number (jika tidak dibutuhkan maka tidak perlu ditambahkan)
- Purchase_Order_Date (jika tidak dibutuhkan maka tidak perlu ditambahkan)
- Item_Number
- Item_Code
- Item_Name
- Quantity
- Inserted_to_Purchase_Order
- Last_Update_By
- Last_Modified_By

Primary Key :
- Purchase_Request_Number
- Item_Number

**Proses / Alurnya adalah sebagai berikut:**
1. User melakukan penambahan pada form Purchase Request dengan memilih barang apa saja yang stok barangnya sudah menipis.
2. Pada saat tambah, nomor PR langsung terbentuk dengan format PR-xxxxxx
3. User memasukkan jumlah barang tersebut sesuai dengan yang dibutuhkan
4. User bisa menghapus / edit pada barang yang salah
5. Jika sudah selesai maka user akan klik tombol "Kirim" untuk masuk ke menu Purchase Order dan dicek oleh PIC bersangkutan.

Note :
1. Jika user menambahkan barang yg sama (double) pada 1 nomor Purchase Request maka barang tersebut akan digabung menjadi satu (mohon dikonfirmasi lagi jika ada perubahan)

**Comment by sevenzk** [comment]
Note 1: yep ini digabung aja kalo ada tambahan.

Di bagian alur no.5

Apakah PIC boleh mengganti Purchase Request qty? Kemarin kayanya sempet diskusi boleh yah?

Dan kalo dari distributor yg sama, kalo PIC mau nambahin itu di PO ato ngulang dari PR ya?

**Comment by WinServer** [comment]
**Apakah PIC boleh mengganti Purchase Request qty? Kemarin kayanya sempet diskusi boleh yah?**
=> Untuk pergantian qty Purchase Request di PO akan coba dijelaskan di issue berikutnya (Purchase Order) dikarenakan ini judulnya Purchase Request, takutnya nanti bingung.

**Dan kalo dari distributor yg sama, kalo PIC mau nambahin itu di PO ato ngulang dari PR ya?**
=> Berdasarkan diskusi terakhir sepertinya kalau tidak salah akan diulang dari PR.

**Comment by sevenzk** [comment]
Woke bung, progress gmn?

Dan 1 lagi form PO bisa di view berdasarkan user kan ya? Ada yg bisa liat items dan QTY, admin dgn harganya.
