### ISSUE TITLE
[Sales Retur] Pembuatan form Sales Retur untuk SPoS

### ISSUE THREAD

**Issue by WinServer** [sevenzk/SJKTCI#351]
Form sales retur akan dibuat seperti gambar berikut:
![image](https://user-images.githubusercontent.com/44515909/125580352-d9d18d1f-266d-49ab-b700-2ce18d58254c.png)

Untuk Detil Returnya adalah sebagai berikut:
![image](https://user-images.githubusercontent.com/44515909/125580779-b03bc776-2bec-4502-ad69-962321abc630.png)

Untuk Detil Barang Returnya adalah sebagai berikut:
![image](https://user-images.githubusercontent.com/44515909/125581099-75a454e1-f82c-4f20-a7bc-92d3c729bd0c.png)

Prosesnya adalah:
1. User akan klik tombol tambah untuk mengisi barang apa yang dikembalikan

2. Setelah klik tambah, User akan mencari nomor Invoice seperti gambar berikut: 
![image](https://user-images.githubusercontent.com/44515909/125580590-5ac6c142-b7d6-4789-9db2-c2160cadc079.png)

3. Kemudian User akan scan Barcode untuk barang yang dikembalikan

4. User akan memilih Tipe Retur seperti gambar berikut:
![image](https://user-images.githubusercontent.com/44515909/125581308-f50345b1-9029-4fc2-ba5b-d69a5f86796c.png)
Tipe Retur ada 4 yaitu:
- Disimpan dan Pengembalian Uang
- Disimpan dan Ditukar
- Dibuang dan Pengembalian Uang
- Dibuang dan Ditukar

5.  Jika tipe retur yang dipilih adalah Disimpan dan Pengembalian Uang, maka informasi Barcode Retur, Kode Retur, dan Nama Retur akan menjadi disable.

6. Hal yang sama juga berlaku untuk tipe retur Dibuang dan Pengembalian Uang.

7. Jika tipe retur yang dipilih adalah Disimpan dan Ditukar, maka User akan melakukan scan barcode untuk Barang Pengganti.

8. Hal yang sama juga berlaku untuk tipe retur Dibuang dan Ditukar. 

9. Setelah selesai semua, User akan klik tombol kunci yang menandakan bahwa proses sudah selesai. Proses kunci ini berfungsi juga untuk menghitung stok jika tipe retur yang dipilih adalah Disimpan dan Pengembalian Uang, Dibuang dan Pengembalian Uang, Dibuang dan Ditukar.

**Comment by sevenzk** [comment]
ok mantab, ini tinggal dibuat bung

**Comment by WinServer** [comment]
refer ke #338
