### ISSUE TITLE
[Penjualan] Data tidak bisa dirubah jika data berasal dari marketplace

### ISSUE THREAD

**Issue by WinServer** [sevenzk/SJKTCI#355]
Data yang berasal dari penjualan marketplace tidak bisa diubah di penjualan PoS dengan tujuan data menjadi sama antara penjualan di marketplace dengan penjualan di PoS.

**Comment by fafn3r** [comment]
sudah diperbaiki dan sudah dipush

**Comment by WinServer** [comment]
Sudah dicoba dan sudah tidak bisa dirubah..jika dirubah harus dari user marketplacenya..
