### ISSUE TITLE
[bug] sjktci spos ikut nemplok ke order entry

### ISSUE THREAD

**Issue by sevenzk** [sevenzk/SJKTCI#356]
![image](https://user-images.githubusercontent.com/14845394/130178136-c3066a3b-5e65-4276-8241-4184965ec07b.png)

kmrn showroom ada bikin supplier baru, BAJU KTC KYTACO supaya bisa jualan. Lalu mereka bikin supplier, bikin PO. barang datang, mereka bikin barcode manual sendiri, input barangnya sudah masuk. lalu horornya pergi ke order entry SJMPOS.

![image](https://user-images.githubusercontent.com/14845394/130178635-64dec955-0d86-4969-a12f-9d07febc8400.png)

**Comment by sevenzk** [comment]
ini yg ktc store 5 dibawah itu kekirim, pdhal bukan tujuannya ke order entry kan ya

**Comment by WinServer** [comment]
berarti ada penambahan filter untuk nama pemasok jika bukan "KTC KYTACO" maka tidak masuk ke order entry pajak maupun non pajak..

**Comment by fafn3r** [comment]
fixed dan sudah dipush
