### ISSUE TITLE
[Master Harga] DPP dibuka untuk penginputan bukan harga setelah pajak

### ISSUE THREAD

**Issue by WinServer** [sevenzk/SJKTCI#36]
yang diinput pertama kali adalah DPP toko..Tampilan menjadi seperti berikut:

![image](https://user-images.githubusercontent.com/44515909/48297457-0bb23800-e4db-11e8-9af7-0108d202d41a.png)

**Comment by sevenzk** [comment]
to be checked again for other bugs

**Comment by WinServer** [comment]
ada perubahan perhitungan di issue yang baru..
