### ISSUE TITLE
Perubahan Konsep Barang di Marketplace

### ISSUE THREAD

**Issue by WinServer** [sevenzk/SJKTCI#363]

**Comment by fafn3r** [comment]
Barang gabungan saat ini terdiri dari komponennya dan gabungannya, jadi semacam ada dobel stok
Untuk konteks marketplace, stok jadi tidak sesuai karena ada dobel stok, jadi untuk barang gabungan hanya dihitung barang gabungannya saja, tanpa dobel stok berupa komponen barang satuannya
