### ISSUE TITLE
Pemindahan Penomoran MNV dari PoS ke MP

### ISSUE THREAD

**Issue by fafn3r** [sevenzk/SJKTCI#364]
Penomoran MNV yang sedang berjalan saat ini, dilakukan di pos sehingga marketplace tidak bisa cetak sebelum menyelesaikan pesanan (mengakibatkan sering terjadinya pembatalan pesanan karena berbagai hal)
karena penomoran MNV tidak perlu dilakukan di pos lagi (dulu PNV, sudah diganti jadi MNV), penomoran MNV ingin dipindahkan ke MP supaya MP bisa langsung cetak di penagihan sebelum menyelesaikan pesanan (dengan tujuan mengurangi kejadian pembatalan pesanan)

**Comment by sevenzk** [comment]
sudah pindah ke iseller
