### ISSUE TITLE
[Daftar Pengepakan] Daftar pengepakan bisa dihapus dan masih ada data barcode list

### ISSUE THREAD

**Issue by WinServer** [sevenzk/SJKTCI#38]
Daftar pengepakan bisa dihapus sedangkan daftar barcode masih ada dengan nomor daftar pengepakan tersebut. Harusnya tidak bisa kecuali daftar barcodenya sudah dihapus.

**Comment by fafn3r** [comment]
fixed, menambahkan flag di packing list sebagai penanda sudah terkirim ke barcode list
packing list yg sudah terkirim ke barcode list tidak bisa diedit/didelete (barcode yang belum terkirim masih bisa diedit/didelete)

**Comment by sevenzk** [comment]
fixed, to be checked again in new version
