### ISSUE TITLE
[Master Harga] Tidak perlu pilih mata uang kembali jika hanya merubah angka dengan mata uang yang sama

### ISSUE THREAD

**Issue by WinServer** [sevenzk/SJKTCI#39]
Jika mata uang sudah terisi dan angkanya sudah terisi kemudian mau ganti angkanya saja maka tidak perlu pilih mata uangnya kembali kecuali mau ganti tipe mata uangnya..

**Comment by fafn3r** [comment]
fixed

**Comment by sevenzk** [comment]
oke fixed
