### ISSUE TITLE
[Number] Dibikin format baru, cek komen

### ISSUE THREAD

**Issue by sevenzk** [sevenzk/SJKTCI#40]
Contoh sales order jadi [SO-0001]
ato Masuk Gudang jadi [MG-0001]

**Comment by sevenzk** [comment]
YY = Year || MM = Month || DD = Day
Ngikut tanggal yg dipilih atau tanggal hari diinput? Kalo backdate jadi ga urut utk tgl dipilih. To be discussed.

Pesanan Pembelian = PP-YYMMDDNNNN
Packing List = PL-YYMMDDNNNN
Barcode List = BL-YYMMDDNNNN
Good Received = GR-YYMMDDNNNN
Store Received = SR-YYMMDDNNNN

Sales Order = SO-YYMMDDNNNN

DSB, males lanjut

**Comment by sevenzk** [comment]
4 YYYY plx

**Comment by fafn3r** [comment]
refer to #98
