### ISSUE TITLE
[PTPOS] Buat future jg, Qty toko ditampilin per item aja kali ya

### ISSUE THREAD

**Issue by sevenzk** [sevenzk/SJKTCI#43]
Buat future program chuwi, item yg punya parent mending yg ditampilin individualnya aja, biar tau ini barangnya sisanya brp.

Setelah dipake brp lama, enakan liat jumlah masing2. Ga usah nge klop smua barang jadi 1

![enhancement](https://user-images.githubusercontent.com/14845394/48612714-5856b100-e9bc-11e8-8e5f-aeca0769adca.PNG)

**Comment by sevenzk** [comment]
Karna sudah jadi barcode 2 2nya, kayanya issue ini secara otomatis fixed.

**Comment by WinServer** [comment]
Done..
