### ISSUE TITLE
[Purchase Order] Sisa Pesanan di PO akan berkurang setelah input data Barcode List

### ISSUE THREAD

**Issue by WinServer** [sevenzk/SJKTCI#47]
Buat PO => Buat Packing List => Buat Barcode List => Sisa pesanan di PO (untuk item bersangkutan) berkurang setelah input jumlah qty item bersangkutan di Barcode List

**Comment by sevenzk** [comment]
Sisa pesanan bisa minus dikarenakan jumlah packing list bisa lebih banyak dari orderan
