### ISSUE TITLE
[Master Harga] jika diinput angka 99.99 perhitungan DPP belum tepat

### ISSUE THREAD

**Issue by WinServer** [sevenzk/SJKTCI#49]
Buat Master Single => Edit harga di Master Harga => Jika diinput 99 perhitungan masih benar, jika diinput 99.99 perhitungan masih belum tepat.

**Comment by fafn3r** [comment]
ternyata memang seperti itu adanya, bukan kesalahan perhitungan, terlampir file excel simulasinya
[Simulasi Perhitungan DPP Berdasarkan Profit %.xlsx](https://github.com/sevenzk/SJKTCI/files/2605282/Simulasi.Perhitungan.DPP.Berdasarkan.Profit.xlsx)

**Comment by sevenzk** [comment]
oke sip betul
