### ISSUE TITLE
[Master Barang Satuan] ubah kapital keubah price level

### ISSUE THREAD

**Issue by sevenzk** [sevenzk/SJKTCI#5]
Kalo kapital diubah, harga jual lv 1 keubah. mending kalo kapital diubah, dikasih notif untuk mau ngubah price level ga? kalo ga mau, harga jualnya jadi 0 smua. to be discussed

**Comment by WinServer** [comment]
Dikasih notif terlebih dahulu, kemudian jika memilih "Yes" mengubah DPP (Pembulatan 1000 ke atas) dan harga jual

**Comment by fafn3r** [comment]
- Jika mengganti mata uang/nilai kapital, diminta konfirmasi untuk mengubah Harga Jual dan DPP berdasarkan Laba (%)
- Dilakukan perhitungan ulang untuk Laba (%) dan Laba (Accounting) berdasarkan DPP dan Kapital baru
