### ISSUE TITLE
[Master Harga] Mungkin buat cost perlu ditampilih dgn 1 tombol

### ISSUE THREAD

**Issue by sevenzk** [sevenzk/SJKTCI#54]
Sperti issue #53 , mungkin ada 1 tombol buat bisa liat/pop up brp "Nilai Tukar", "Pengiriman", sepertinya ada tambahan di setting seperti "bunga bank" dan "advertising"

**Comment by WinServer** [comment]
Ketika klik tombol "Perincian" maka akan muncul satu form untuk mempelihatkan "Nilai Tukar", "Pengiriman", "bunga bank" dan "advertising".

Yang bisa klik tombol ini hanya user admin (termasuk laba dan kapital).
