### ISSUE TITLE
[Master Pengaturan] Perhitungan rumus untuk HPP modal

### ISSUE THREAD

**Issue by WinServer** [sevenzk/SJKTCI#63]
Rumus untuk perhitungan HPP modal adalah:
A = Kapital * Exchange Rate
B = Shipping
C = Bunga
D = Advertising

Rumusan HPP modal= (((A*((100+B)/100)) * ((100+C)/100)) * ((100+D)/100))

**Comment by sevenzk** [comment]
Oke, mungkin ada tambahan hoho
