### ISSUE TITLE
[Search] Bisa search exact item

### ISSUE THREAD

**Issue by sevenzk** [sevenzk/SJKTCI#68]
Mungkin dengan cara pake kutip? "yolo" cman yolo yg keluar, "yolo master" ato "yolo alone" ga kliatan.

**Comment by WinServer** [comment]
Kondisi pada saat search :
1. Jika pada saat klik search ada tanda baca " maka query yang digunakan adalah =..
2. Jika tidak ada tanda baca " maka query yang digunakan adalah like..

**Comment by sevenzk** [comment]
karna skarang sudah bisa excel, gua close ini aja.
