### ISSUE TITLE
[Daftar Pengepakan dan Barcode] Untuk nomor Barcode dibuat auto generate

### ISSUE THREAD

**Issue by WinServer** [sevenzk/SJKTCI#71]
Format nomor barcode menjadi [Kode Supplier-yyyymmddnnnnn]
Jadi misalnya nama suppluer Fuzhou dan kodenya adalah FZ maka nomor barcodenya menjadi : 
FZ-201812010001

Misalnya ada 2 supplier pada saat pengisian Daftar Pengepakan dan Barcode maka nomornya mengikuti nomor terakhir.
Sebagai contoh :
FZ-201812010001
FZ-201812010002
GR-201812010003

**Comment by WinServer** [comment]
setelah menarik nama supplier dan nomor PO maka Isi Otomatis ter-enabled dan kurang kode "-"

**Comment by fafn3r** [comment]
fixed

**Comment by WinServer** [comment]
Pada saat pembuatan barcode karton minta dimunculkan pop up "Please Wait......"

Masih bisa paste karakter di kolom bagian jumlah.....

Masih bisa disave angka 0 di kolom jumlah Packing Barcode List....

Dibuatkan export ke excel untuk nomor barcode dari Packing List....

Format Tahun di nomor Barcode diubah menjadi 2 digit...

**Comment by WinServer** [comment]
Done..
