### ISSUE TITLE
[Warehouse to Store] Pembuatan form WTS seperti GR

### ISSUE THREAD

**Issue by WinServer** [sevenzk/SJKTCI#73]
Akan dibuatkan form WTS seperti form GR dan dijadikan satu dengan program GR (ada pilihan mau GR atau WTS).

Untuk quantity sudah bisa dibuat untuk penambahan warehouse qty (GR)
Untuk quantity sudah bisa dibuat untuk pengurangan warehouse qty dan penambahan store qty (WTS)

**Comment by WinServer** [comment]
![image](https://user-images.githubusercontent.com/44515909/49560470-1ed2ef00-f945-11e8-93f8-2db087d0885b.png)

Untuk databasenya apakah mau dijadikan satu tersendiri atau dipisah (GR in dan GR out) atau opsi lain di database GR ada flag penanda in dan out..

Untuk WTS pakai table WTS yang sudah cuma dirubah sama seperti GR..

**Comment by fafn3r** [comment]
ditunjukkan pada Sabtu, 8 Desember 2018

**Comment by WinServer** [comment]
Pencarian barcode masih menggunakan function "Like" bukan "="

**Comment by fafn3r** [comment]
fixed

**Comment by WinServer** [comment]
Done
