### ISSUE TITLE
[Master Harga] Pembulatan diganti menjadi pembulatan 500

### ISSUE THREAD

**Issue by WinServer** [sevenzk/SJKTCI#76]
Angka pembulatan menjadi 500.
Misal : 170.011 menjadi 170.500
Jika     170.511 menjadi 171.000

**Comment by WinServer** [comment]
di DPP tertinggi tidak dibulatkan namun yang lainnya sudah dibulatkan

![image](https://user-images.githubusercontent.com/44515909/49980129-cf17a780-ff84-11e8-9748-9e7e930afe2c.png)

**Comment by sevenzk** [comment]
sudah dicopot.
