### ISSUE TITLE
[Master Harga] HET data gabungan akan didiskon 5% dan menjadi HET tertinggi terbaru

### ISSUE THREAD

**Issue by WinServer** [sevenzk/SJKTCI#77]
HET barang gabungan = total HET tertinggi - (total HET tertinggi * 5%)
Diskon lvl 1 = 40%
Diskon lvl 2 = 25%
Diskon lvl 3= 15%
Diskon lvl 4 = 10%

dan bisa diedit kembali angkanya

**Comment by sevenzk** [comment]
Mungkin di bagian sini boleh dilampirkan dimana gitu, di show total HET tertingginya dengan 1 tombol atau gmn?

**Comment by fafn3r** [comment]
untuk perhitungan harga barang gabungan, ada 2 kemungkinan:
1. Semua harga dihitung 95% dari total harga komponen gabungan (semua harga pasti lebih murah dari total harga komponennya)
2. HET dihitung 95% dari total HET komponen, lalu Harga Lv 1-Lv 4 dihitung dengan persentase diskon yang sudah ditentukan (40, 25, 15, 10) dari HET (ada kemungkinan lebih mahal dari total harga masing2 komponennya, karena hanya mengacu ke HET yang 95% total HET komponen)

**Comment by sevenzk** [comment]
Lebih ke nomor 1 sih. Biar ga pusing.

**Comment by sevenzk** [comment]
Karna belum di close, jadi ditambahin aja disini.

Harga gabungan diberi opsi centang atau something kalau gabungan tersebut perlu di diskon atau ngga.

Contoh ada bbrp barang akan cari harga GPMnya dl, tapi kita akan menjualnya secara set, karna tidak dijual 1an, jadi disini mending tidak di diskon untuk barang tersebut.

**Comment by WinServer** [comment]
sudah dipindah ke wiki ya..
