### ISSUE TITLE
[Barcode List Barang] Apakah perlu kode khusus sehingga tidak perlu dicatat di dalam aplikasi semua barcode list barang

### ISSUE THREAD

**Issue by WinServer** [sevenzk/SJKTCI#84]
sebagai contoh :
Barang dop busi mempunyai kode barcode DOB20181212001
Barang selang bensin mempunyai kode barcode SLB20181212001

Sehingga pada saat scan barcode barang keluar, aplikasi membaca 3 huruf depan kode tersebut.
Kode ini dibuat di masing-masing item (Item satuan, gabungan, dan set).

Sehingga barcode list akan tercatat pada saat pernjualan/SO dimana pada saat scan barcode barang ada informasi tambahan barcode untuk barang tersebut.

need to be discussed.

**Comment by sevenzk** [comment]
Let's discuss it later

**Comment by WinServer** [comment]
sudah didiskusikan dan dibuat menjadi 4 karakter untuk kode barang..
