### ISSUE TITLE
[Harga] Cara hitung dari awal sampai akhir

### ISSUE THREAD

**Issue by sevenzk** [sevenzk/SJKTCI#88]
Opsi yang perlu ada di Settings

- Exchange Rate / Nilai Tukar
- Customs / Bea
- Shipping / Pengiriman
- Bank Interest / Bunga Bank

- Capital * Exchange rate * Customs * Shipping * Bank Interest = HPP Indon (formulanya ampe sini, ads ternyata mesti masuk di budgeting di expense.

- HPP Indon + Profit Margin Wholesale = GPM W

Bagian ini mesti diulang dengan jurus yang dulu rupanya
eg.
- 100.000 + 30% = GPM W
- GPM W = 100.000 / 0.7 + (berat * ongkir per KG)
- GPM W = 142.857.14 + (0 * 100rb)

Dah dari sini baru cari HET.

- HET = (142.857.14 / 0.6)
- HET = 238.095.23 

SW adalah 25% dari HET
- GPM SW = 238.095.23 - 25%
- GPM SW = 178.571.42

R juga sama dari HET.

Itungan terakhir adalah ongkir. Itu kayanya mesti ktemu ngobrol baru bisa jelasin.

**Comment by WinServer** [comment]
Iklan dibuang dari master pengaturan..

HPP dimunculkan di master harga (di bagian perincian) dimana HPP akan berubah jika capital berubah berdasarkan rumus di atas...

Diskon level 1 (W), level 2 (SW), level 3 (R), level 4 (TO) dibuang dari master harga..Yang diisi hanyalah Laba (Profit Margin) untuk perhitungan HPP indon dan menghitung lvl 1 terlebih dahulu kemudian menghitung HET tertinggi baru level 2, 3, dan 4...

Harga level 1 (W) = 40% dari HET tertinggi
Harga level 2 (SW) = 25% dari HET tertinggi
Harga level 3 (R) = 15% dari HET tertinggi
Harga level 4 (TO) = HET tertinggi

**Comment by WinServer** [comment]
akan dicek terlebih dahulu..

**Comment by sevenzk** [comment]
sudah benar, amin

**Comment by sevenzk** [comment]
DPP diganti jadi GPM

HET
GPM W
GPM SW
GPM B
GPM TO

Yg sebelah kiri juga sama, tapi di kedua kolom ditambahkan teks, SEBELUM PAJAK, SESUDAH PAJAK.

**Comment by sevenzk** [comment]
Setelah go live, ada bbrp angka yang tidak sesuai

Harga level 1 (W) = 40% dari HET tertinggi
Harga level 2 (SW) = 25% dari HET tertinggi
Harga level 3 (RS) = 15% dari HET tertinggi
Harga level 4 (HET) = HET tertinggi

menjadi

Harga level 1 (W) = 40% dari HET tertinggi
Harga level 2 (SW) = 30% dari HET tertinggi
Harga level 3 (R) = 25% dari HET tertinggi
Harga level 4 (TO) = HET tertinggi

**Comment by WinServer** [comment]
sudah dipindah ke wiki..
