### ISSUE TITLE
[Rasio Barang] Penambahan form baru untuk melihat rasio barang per distributor

### ISSUE THREAD

**Issue by WinServer** [sevenzk/SJKTCI#91]
Penambahan form baru untuk melihat rasio barang per distributor per bulan dimana rasionya 85% untuk barang fast moving, 15% untuk barang slow moving...

Acuan angkanya adalah harga MOQ senilai 150.000.000 dimana perhitungan harga barang untuk per distributor ditotal dan disajikan dalam bentuk persentase..

Untuk barang fast moving dan slow moving dibedakan di master item single..
Jika memungkinkan master item gabungan tidak perlu ada flag barang fast moving dan slow moving dimana master barang gabungan dilihat ke master item single..

**Comment by fafn3r** [comment]
klasifikasi barang "Cepat"/"Lambat" sudah ditambahkan di Master Item Single

**Comment by sevenzk** [comment]
Gile desember 2018, dah lama jg ini. Boleh nih dipikirkan di desember 2020

**Comment by WinServer** [comment]
Untuk hal ini, ada perubahan di **master item single** dimana flag hanya gabungan akan dijadikan satu di bagian klasifikasi dimana informasi klasifikasi ada Cepat, Lambat, dan Gabungan.

Untuk form rasio ini akan berisi seperti gambar berikut:
![image](https://user-images.githubusercontent.com/44515909/77218877-a7899480-6b62-11ea-99b3-4e954a577011.png)

**Comment by WinServer** [comment]
bisa dipikirkan kembali di 2025
