### ISSUE TITLE
[Master Barang Satuan] Ditambahkan informasi berat barang dan item Code wajib 4 karakter

### ISSUE THREAD

**Issue by WinServer** [sevenzk/SJKTCI#92]
Penambahan kolom berat barang untuk perhitungan ongkos kirim barang..

Penambahan kolom kode barang wajib 4 karakter (tidak boleh kurang dan lebih) untuk keperluan scan barcode

**Comment by fafn3r** [comment]
sudah ditambahkan, belum jadi primary key karena datanya masih kosong
to be discussed apakah mau jadi unique seperti di master supplier

**Comment by WinServer** [comment]
Harus unique dikarenakan kode antar barang tidak boleh sama..jika sama maka harusnya ada penolakan atau validasi "Kode barang ini sudah digunakan"...

**Comment by fafn3r** [comment]
noted, as of now belum bisa jadi unique karena datanya masih kosong, buat temporary data?

**Comment by WinServer** [comment]
iyah..buat temporary data..

**Comment by WinServer** [comment]
sudah oke
