### ISSUE TITLE
[Pareto] System baru untuk melihat prediksi penjualan barang

### ISSUE THREAD

**Issue by WinServer** [sevenzk/SJKTCI#95]
System akan dibuat untuk melihat prediksi hasil penjualan barang (apakah barang tersebut laku dalam penjualan atau tidak).

System akan disajikan dalam bentuk grafik penjualan..

**Comment by WinServer** [comment]
Untuk saat ini contohnya adalah sebagai berikut :
![image](https://user-images.githubusercontent.com/44515909/75410209-a7282000-594d-11ea-9043-7b4b7378d446.png)

penjelasannya kurang lebih seperti ini:
- Gambar ke - 1 menunjukkan penjualan di bulan February 2020 dimana dapat terlihat dari semua barang yang terjual, yang plaing signifikan untuk penjualan adalah MZ 40 (39.5%) dari semua barang

- Gambar ke - 2 menunjukkan dari semua distributor di bulan February 2020 dapat terlihat bahwa untuk distributor Awi menunjukkan pembelian yg signifikan sebesar 25% dari semua pembelian distrbutor.

Untuk saat ini apakah seperti ini yang dibutuhkan?..
mohon koreksi ya jika ada masukan..

**Comment by sevenzk** [comment]
Tetet, menurut gua yg diminta ko budi itu semacam prediksi 1 item, penjualan dalam 1 tahunnya begimana. Rame pas kapan, di bulan apa, di minggu mana. Dsb dsb.

Untuk bagian 2, mungkin komparasi si Awi beli Pz Tiger 40nya dibanding distributor yg lain. Dan ga bisa pakai sample 1 bln doank sih spertinya.

**Comment by WinServer** [comment]
okehh sur..gw coba analisa lagi..

untuk point nomor 2 apakah seperti ini sur:
![image](https://user-images.githubusercontent.com/44515909/75413177-70570780-5957-11ea-939a-bcc11c10b288.png)

Jadi nanti sebelum muncul grafiknya, ada pilih dari bulan berapa sampai bulan berapa dan barangnya apa..

**Comment by fafn3r** [comment]
info ko budi:
- gambar pertama sudah oke
- gambar kedua perlunya per distributor tapi didetailkan barangnya apa saja

**Comment by WinServer** [comment]
sepp..thank you..nanti kita bahas lebih lanjut di hari sabtu haha..

**Comment by WinServer** [comment]
Setelah berdiksusi, hasil pareto adalah sebagai berikut:
![image](https://user-images.githubusercontent.com/44515909/75600693-0704ff00-5ae5-11ea-997d-88f956e6572b.png)

Keterangan:
1. Gambar pertama menjelaskan 10 Barang terjual terbanyak selama 1 tahun (tampilan 10 barang dan per tahun)
2. Gambar kedua menjelaskan 10 Barang terjual terbanyak untuk masing-masing distributor (tampilan 10 barang dan per tahun)
3. Gambar ketiga menjelaskan Barang yang terjual selama 1 tahun (tampilan per tahun untuk masing-masing bulan)

- Gambar ke - 2 dan ke - 3 mempunyai tombol Previous dan Next untuk perpindahan data
- Data yang diambil adalah real time (harus ada proses refresh setiap 1 jam / 2 jam)
- Data laporan akan ditampilkan dalam bentuk web dan akan dipasang di monitor / TV untuk dilihat setiap harinya

**Comment by WinServer** [comment]
1. harus dibuat setting refresh data otomatis setiap 2 jam.
2. ada tambahan analisa untuk prediksi penjualan barang.
3. satu layar dimunculkan 3 windows berbarengan.

**Comment by WinServer** [comment]
akan ada penambahan filter di masa depan
