### ISSUE TITLE
[Packing List] Kode barcode berubah untuk tahun dan bulan menjadi huruf

### ISSUE THREAD

**Issue by WinServer** [sevenzk/SJKTCI#98]
Kode Barcode di packing list berubah menjadi SMT1AA0001 dengan rincian :
SMT1 = Kode Barang di master barang
A = Tahun 2019
A = Bulan 1
0001 = Urutan barcode

untuk kode tahun menjadi :
A=19; B=20; C=21; D=22; E=23, dst.....

untuk kode bulan menjadi :
A=1; B=2; C=3; D=4; E=5; F=6; G=7; H=8; I=9; J=10; K=11; L=12

**Comment by sevenzk** [comment]
Diskusi dari Pak Budi, BFTM0A00001

BTFM masih sama
0 itu 2020, jadi kalo 2019 jadi BFTM9

A masih bulan, tapi bisa di formulasikan buat dari A-Z skipnya bagus buat 12 bulan? Biar ga ngurus A-Lnya.

Untuk digitnya, ada bbrp barang bisa puluhan ribu, by default 4 aja trus kalo ada ampe 5 digit baru ke edit, apa lgs default 5 digit?

**Comment by WinServer** [comment]
Untuk format nya menjadi 0S01-19A0001 dengan rincian sebagai berikut :
0S01 = Kode Supplier
19 = Tahun 
A = Bulan
0001 = Urutan Barcode

Untuk bulan kodenya adalah sebagai berikut :
A = 1, C = 2, F = 3, H = 4, I = 5, K = 6, M = 7, N = 8, P = 9, S = 10, V = 11, Z = 12

**Comment by WinServer** [comment]
Done..sudah dirubah menjadi huruf..
